# Manipulación de Fechas y Datetime en Python

Este notebook documenta las principales técnicas para trabajar con fechas y horas en Python, cubriendo:

- **Módulo datetime nativo de Python**
- **NumPy datetime64**
- **Pandas datetime y manipulación de series temporales**

---

## 📖 Contenido

1. [Importar Librerías Necesarias](#1)
2. [Códigos de Formato Datetime](#2)
3. [Funciones Básicas de Datetime](#3)
4. [Conversión entre Cadenas y Objetos Datetime](#4)
5. [Manipulación de Zonas Horarias](#5)
6. [Trabajo con Timestamps](#6)
7. [Datetime en NumPy](#7)
8. [Datetime en Pandas - Conversión y Creación](#8)
9. [Accesor dt en Pandas Series](#9)
10. [Operaciones Avanzadas con Fechas en Pandas](#10)
11. [Filtrado y Selección por Fechas](#11)
12. [Resampleo y Agrupación Temporal](#12)

## 1. Importar Librerías Necesarias {#1}

Para trabajar con fechas y horas en Python necesitamos importar las siguientes librerías:

In [26]:
# Importar librerías necesarias
from datetime import datetime, date, time, timedelta, timezone
import pandas as pd
import numpy as np
import pytz
from pytz import timezone as pytz_timezone
import warnings
warnings.filterwarnings('ignore')

print("✅ Librerías importadas correctamente")
print(f"📦 Pandas version: {pd.__version__}")
print(f"📦 NumPy version: {np.__version__}")
print(f"📦 pytz version: {pytz.__version__}")

✅ Librerías importadas correctamente
📦 Pandas version: 2.2.3
📦 NumPy version: 1.26.4
📦 pytz version: 2025.1

## 2. Códigos de Formato Datetime {#2}

Los códigos de formato son fundamentales para convertir entre objetos datetime y cadenas de texto. Aquí están todos los códigos disponibles con ejemplos prácticos:

In [ ]:
# Crear una fecha ejemplo para demostrar todos los formatos
fecha_ejemplo = datetime(2024, 1, 15, 14, 30, 45)  # 15 de enero 2024, 2:30:45 PM
print(f"Fecha ejemplo: {fecha_ejemplo}")
print("=" * 60)

# Tabla de códigos de formato con ejemplos reales
formatos = [
    ('%a', 'Día de la semana abreviado', fecha_ejemplo.strftime('%a')),
    ('%A', 'Día de la semana completo', fecha_ejemplo.strftime('%A')),
    ('%b', 'Mes abreviado', fecha_ejemplo.strftime('%b')),
    ('%B', 'Nombre del mes completo', fecha_ejemplo.strftime('%B')),
    ('%c', 'Fecha y hora completa', fecha_ejemplo.strftime('%c')),
    ('%d', 'Día (con ceros)', fecha_ejemplo.strftime('%d')),
    ('%H', '24 horas', fecha_ejemplo.strftime('%H')),
    ('%I', '12 horas', fecha_ejemplo.strftime('%I')),
    ('%j', 'Día del año', fecha_ejemplo.strftime('%j')),
    ('%m', 'Mes', fecha_ejemplo.strftime('%m')),
    ('%M', 'Minuto', fecha_ejemplo.strftime('%M')),
    ('%p', 'AM o PM', fecha_ejemplo.strftime('%p')),
    ('%S', 'Segundos', fecha_ejemplo.strftime('%S')),
    ('%U', 'Número de semana (Dom)', fecha_ejemplo.strftime('%U')),
    ('%W', 'Número de semana (Lun)', fecha_ejemplo.strftime('%W')),
    ('%w', 'Día de la semana (0-6)', fecha_ejemplo.strftime('%w')),
    ('%x', 'Fecha local', fecha_ejemplo.strftime('%x')),
    ('%X', 'Hora local', fecha_ejemplo.strftime('%X')),
    ('%y', 'Año sin siglo', fecha_ejemplo.strftime('%y')),
    ('%Y', 'Año completo', fecha_ejemplo.strftime('%Y')),
    ('%z', 'Desplazamiento UTC', fecha_ejemplo.strftime('%z')),
    ('%Z', 'Zona horaria', fecha_ejemplo.strftime('%Z'))
]

# Mostrar tabla formateada
print(f"{'Código':<8} {'Descripción':<30} {'Ejemplo':<20}")
print("-" * 60)
for codigo, descripcion, ejemplo in formatos:
    print(f"{codigo:<8} {descripcion:<30} {ejemplo:<20}")

Fecha ejemplo: 2024-01-15 14:30:45
============================================================
Código   Descripción                    Ejemplo
------------------------------------------------------------
%a       Día de la semana abreviado     Mon
%A       Día de la semana completo      Monday
%b       Mes abreviado                  Jan
%B       Nombre del mes completo        January
%c       Fecha y hora completa          Mon Jan 15 14:30:45 2024
%d       Día (con ceros)                15
%H       24 horas                       14
%I       12 horas                       02
%j       Día del año                    015
%m       Mes                            01
%M       Minuto                         30
%p       AM o PM                        PM
%S       Segundos                       45
%U       Número de semana (Dom)         02
%W       Número de semana (Lun)         03
%w       Día de la semana (0-6)         1
%x       Fecha local                    01/15/24
%X       Hora local                     14:30:45
%y       Año sin siglo                  24
%Y       Año completo                   2024
%z       Desplazamiento UTC
%Z       Zona horaria

## 3. Funciones Básicas de Datetime {#3}

Las funciones principales para manipular objetos datetime son `strptime()` (string to datetime) y `strftime()` (datetime to string):

In [ ]:
# 1. strptime() - Convertir string a datetime
fecha_string = "25/11/2022"
dt_object = datetime.strptime(fecha_string, "%d/%m/%Y")
print(f"String: '{fecha_string}' → Datetime: {dt_object}")
print(f"Tipo: {type(dt_object)}")
print()

String: '25/11/2022' → Datetime: 2022-11-25 00:00:00
Tipo: <class 'datetime.datetime'>

In [ ]:

# 2. strftime() - Convertir datetime a string
fecha_formateada = dt_object.strftime("%d/%m/%Y")
print(f"Datetime: {dt_object} → String: '{fecha_formateada}'")
print(f"Tipo: {type(fecha_formateada)}")
print()

Datetime: 2022-11-25 00:00:00 → String: '25/11/2022'
Tipo: <class 'str'>

In [ ]:

# 3. timestamp() - Convertir a timestamp Unix
timestamp_unix = dt_object.timestamp()
print(f"Datetime: {dt_object} → Timestamp: {timestamp_unix}")
print(f"Tipo: {type(timestamp_unix)}")
print()

Datetime: 2022-11-25 00:00:00 → Timestamp: 1669345200.0
Tipo: <class 'float'>

In [ ]:

# 4. fromtimestamp() - Convertir timestamp a datetime
dt_from_timestamp = datetime.fromtimestamp(timestamp_unix)
print(f"Timestamp: {timestamp_unix} → Datetime: {dt_from_timestamp}")
print()

Timestamp: 1669345200.0 → Datetime: 2022-11-25 00:00:00

In [1]:
import time

In [25]:
time.time()

1759590538.995317

In [28]:
datetime.now()

datetime.datetime(2025, 10, 4, 12, 9, 59, 416786)

In [29]:

# 5. Conversión directa string a string con formato diferente
nueva_fecha = datetime.strptime("25/11/2022", "%d/%m/%Y").strftime("%Y-%m-%d")
print(f"Conversión directa: '25/11/2022' → '{nueva_fecha}'")

Conversión directa: '25/11/2022' → '2022-11-25'

## 4. Conversión entre Formatos de 12 y 24 Horas {#4}

Ejemplos de conversión entre formatos de hora:

In [30]:
# Conversión de 24 horas a 12 horas (AM/PM)
hora_24 = "20:00"
hora_12 = datetime.strptime(hora_24, "%H:%M").strftime("%I:%M %p")
print(f"24 horas: {hora_24} → 12 horas: {hora_12}")

24 horas: 20:00 → 12 horas: 08:00 PM

In [31]:

# Conversión de 12 horas (AM/PM) a 24 horas
hora_pm = "08:00 PM"
hora_24_convertida = datetime.strptime(hora_pm, "%I:%M %p").strftime("%H:%M")
print(f"12 horas: {hora_pm} → 24 horas: {hora_24_convertida}")

12 horas: 08:00 PM → 24 horas: 20:00

In [32]:

# Más ejemplos
ejemplos_conversion = [
    ("14:30", "%H:%M", "%I:%M %p"),
    ("02:15 AM", "%I:%M %p", "%H:%M"),
    ("11:45 PM", "%I:%M %p", "%H:%M"),
    ("09:00", "%H:%M", "%I:%M %p")
]

print("\n🔄 Tabla de conversiones:")
print(f"{'Entrada':<15} {'Formato Entrada':<15} {'Salida':<15} {'Formato Salida'}")
print("-" * 65)

for entrada, fmt_entrada, fmt_salida in ejemplos_conversion:
    salida = datetime.strptime(entrada, fmt_entrada).strftime(fmt_salida)
    print(f"{entrada:<15} {fmt_entrada:<15} {salida:<15} {fmt_salida}")

🔄 Tabla de conversiones:
Entrada         Formato Entrada Salida          Formato Salida
-----------------------------------------------------------------
14:30           %H:%M           02:30 PM        %I:%M %p
02:15 AM        %I:%M %p        02:15           %H:%M
11:45 PM        %I:%M %p        23:45           %H:%M
09:00           %H:%M           09:00 AM        %I:%M %p

## 5. Manipulación de Zonas Horarias {#5}

Trabajar con diferentes zonas horarias usando `pytz`:

In [33]:
# Ejemplo del documento: Nueva York a Tokyo
ny_time_str = "25-11-2022 09:34:00-0700"
ny_time = datetime.strptime(ny_time_str, "%d-%m-%Y %H:%M:%S%z")
print(f"Hora en Nueva York: {ny_time}")

Hora en Nueva York: 2022-11-25 09:34:00-07:00

In [34]:

# Convertir a Tokyo
tokyo_tz = pytz_timezone('Asia/Tokyo')
tokyo_time = ny_time.astimezone(tokyo_tz)
print(f"Hora en Tokyo: {tokyo_time}")
print()

Hora en Tokyo: 2022-11-26 01:34:00+09:00

In [35]:

# Trabajar con zonas horarias comunes
zonas_horarias = ['UTC', 'US/Eastern', 'US/Pacific', 'Europe/London', 
                  'Europe/Madrid', 'Asia/Tokyo', 'Australia/Sydney', 'America/Buenos_Aires']

# Crear fecha con timezone UTC
utc_time = datetime.now(pytz.UTC)
print(f"Hora UTC actual: {utc_time}")
print("\n🌍 Conversión a diferentes zonas horarias:")
print("-" * 50)

for zona in zonas_horarias:
    tz = pytz_timezone(zona)
    hora_local = utc_time.astimezone(tz)
    print(f"{zona:<20}: {hora_local.strftime('%Y-%m-%d %H:%M:%S %Z')}")

# Ejemplo práctico: Programar una reunión internacional
print("\n📅 Ejemplo: Reunión a las 15:00 hora de Madrid")
madrid_tz = pytz_timezone('Europe/Madrid')
reunion_madrid = madrid_tz.localize(datetime(2024, 3, 15, 15, 0, 0))

print(f"Madrid: {reunion_madrid.strftime('%H:%M %Z')}")
print(f"Nueva York: {reunion_madrid.astimezone(pytz_timezone('US/Eastern')).strftime('%H:%M %Z')}")
print(f"Tokyo: {reunion_madrid.astimezone(pytz_timezone('Asia/Tokyo')).strftime('%H:%M %Z')}")
print(f"Los Angeles: {reunion_madrid.astimezone(pytz_timezone('US/Pacific')).strftime('%H:%M %Z')}")
print(f"Buenos Aires: {reunion_madrid.astimezone(pytz_timezone('America/Buenos_Aires')).strftime('%H:%M %Z')}")

Hora UTC actual: 2025-10-04 15:11:38.606859+00:00

🌍 Conversión a diferentes zonas horarias:
--------------------------------------------------
UTC                 : 2025-10-04 15:11:38 UTC
US/Eastern          : 2025-10-04 11:11:38 EDT
US/Pacific          : 2025-10-04 08:11:38 PDT
Europe/London       : 2025-10-04 16:11:38 BST
Europe/Madrid       : 2025-10-04 17:11:38 CEST
Asia/Tokyo          : 2025-10-05 00:11:38 JST
Australia/Sydney    : 2025-10-05 01:11:38 AEST
America/Buenos_Aires: 2025-10-04 12:11:38 -03

📅 Ejemplo: Reunión a las 15:00 hora de Madrid
Madrid: 15:00 CET
Nueva York: 10:00 EDT
Tokyo: 23:00 JST
Los Angeles: 07:00 PDT
Buenos Aires: 11:00 -03

## 6. Trabajo con Timestamps {#6}

Los timestamps representan el tiempo como segundos desde el 1 de enero de 1970 (época Unix):

In [36]:
# Obtener timestamp actual
ahora = datetime.now()
timestamp_actual = ahora.timestamp()
print(f"Fecha actual: {ahora}")
print(f"Timestamp actual: {timestamp_actual}")
print()

Fecha actual: 2025-10-04 12:12:16.768878
Timestamp actual: 1759590736.768878

In [15]:

# Convertir timestamp específico a datetime
timestamp_ejemplo = 1617836400.0
fecha_desde_timestamp = datetime.fromtimestamp(timestamp_ejemplo)
print(f"Timestamp: {timestamp_ejemplo}")
print(f"Fecha: {fecha_desde_timestamp}")
print(f"Fecha formateada: {fecha_desde_timestamp.strftime('%d/%m/%Y %H:%M:%S')}")
print()

Timestamp: 1617836400.0
Fecha: 2021-04-07 20:00:00
Fecha formateada: 07/04/2021 20:00:00

In [17]:

# Operaciones útiles con timestamps
print("📊 Operaciones con timestamps:")

# Calcular diferencia en días
fecha1 = datetime(2024, 1, 1)
fecha2 = datetime(2024, 12, 31)
timestamp1 = fecha1.timestamp()
timestamp2 = fecha2.timestamp()

diferencia_segundos = timestamp2 - timestamp1
diferencia_dias = diferencia_segundos / (24 * 60 * 60)

print(f"Fecha 1: {fecha1.strftime('%d/%m/%Y')}")
print(f"Fecha 2: {fecha2.strftime('%d/%m/%Y')}")
print(f"Diferencia en segundos: {diferencia_segundos:,.0f}")
print(f"Diferencia en días: {diferencia_dias:,.0f}")

📊 Operaciones con timestamps:
Fecha 1: 01/01/2024
Fecha 2: 31/12/2024
Diferencia en segundos: 31,536,000
Diferencia en días: 365

In [18]:

# Timestamps para diferentes momentos del día
print("\n⏰ Timestamps para diferentes horas:")
base_fecha = datetime(2024, 6, 15)
horas = [0, 6, 12, 18, 23]

for hora in horas:
    fecha_hora = base_fecha.replace(hour=hora)
    timestamp = fecha_hora.timestamp()
    print(f"{fecha_hora.strftime('%H:%M')}: {timestamp:,.0f}")

⏰ Timestamps para diferentes horas:
00:00: 1,718,420,400
06:00: 1,718,442,000
12:00: 1,718,463,600
18:00: 1,718,485,200
23:00: 1,718,503,200

## 7. Datetime en NumPy {#7}

NumPy proporciona tipos `datetime64` y `timedelta64` para operaciones eficientes con arrays de fechas:

In [37]:
# Crear datetime64 en NumPy
fecha_numpy = np.datetime64('2024-03-15')
print(f"Fecha NumPy: {fecha_numpy}")
print(f"Tipo: {type(fecha_numpy)}")
print()

Fecha NumPy: 2024-03-15
Tipo: <class 'numpy.datetime64'>

In [38]:

# Crear array de fechas
fechas_array = np.array(['2024-01-01', '2024-06-15', '2024-12-31'], dtype='datetime64')
print(f"Array de fechas: {fechas_array}")
print(f"Tipo del array: {fechas_array.dtype}")
print()

Array de fechas: ['2024-01-01' '2024-06-15' '2024-12-31']
Tipo del array: datetime64[D]

In [39]:

# Diferentes unidades de tiempo
print("🕒 Diferentes precisiones temporales:")
fecha_base = '2024-03-15T14:30:45'
unidades = ['D', 'h', 'm', 's', 'ms', 'us', 'ns']

for unidad in unidades:
    fecha_unidad = np.datetime64(fecha_base, unidad)
    print(f"Unidad '{unidad}': {fecha_unidad}")

🕒 Diferentes precisiones temporales:
Unidad 'D': 2024-03-15
Unidad 'h': 2024-03-15T14
Unidad 'm': 2024-03-15T14:30
Unidad 's': 2024-03-15T14:30:45
Unidad 'ms': 2024-03-15T14:30:45.000
Unidad 'us': 2024-03-15T14:30:45.000000
Unidad 'ns': 2024-03-15T14:30:45.000000000

In [41]:

# Crear rangos de fechas con NumPy
print("\n📅 Rangos de fechas con NumPy:")
rango_fechas = np.arange('2024-01-01', '2024-01-08', dtype='datetime64[D]')
print(f"Semana completa: {rango_fechas}")

📅 Rangos de fechas con NumPy:
Semana completa: ['2024-01-01' '2024-01-02' '2024-01-03' '2024-01-04' '2024-01-05'
 '2024-01-06' '2024-01-07']

In [42]:

# Operaciones aritméticas
print("\n🧮 Aritmética con datetime64:")
fecha_inicio = np.datetime64('2024-01-01')
dias_agregar = np.timedelta64(30, 'D')
fecha_final = fecha_inicio + dias_agregar

print(f"Fecha inicio: {fecha_inicio}")
print(f"Agregar: {dias_agregar}")
print(f"Fecha final: {fecha_final}")

🧮 Aritmética con datetime64:
Fecha inicio: 2024-01-01
Agregar: 30 days
Fecha final: 2024-01-31

In [43]:

# Calcular diferencias
fecha1 = np.datetime64('2024-12-31')
fecha2 = np.datetime64('2024-01-01')
diferencia = fecha1 - fecha2
print(f"\nDiferencia entre {fecha1} y {fecha2}: {diferencia}")

Diferencia entre 2024-12-31 y 2024-01-01: 365 days

In [44]:

# Array de timedelta
print("\n⏱️ Array de timedeltas:")
duraciones = np.array([1, 7, 30, 365], dtype='timedelta64[D]')
print(f"Duraciones en días: {duraciones}")

⏱️ Array de timedeltas:
Duraciones en días: [  1   7  30 365]

In [45]:

# Convertir duraciones a diferentes unidades
print(f"En horas: {duraciones.astype('timedelta64[h]')}")
print(f"En semanas: {duraciones.astype('timedelta64[W]')}")

En horas: [  24  168  720 8760]
En semanas: [ 0  1  4 52]

## 8. Datetime en Pandas - Conversión y Creación {#8}

Pandas ofrece herramientas poderosas para trabajar con series temporales y convertir datos de fecha:

In [46]:
# Ejemplo del documento: convertir strings a datetime
data = ['2023-01-20', '2023-04-27', '2023-06-15']
my_series = pd.Series(data)
print("Serie original (strings):")  
display(my_series) # display solo en jupyter
print(f"Tipo de datos: {my_series.dtype}")
print()

Serie original (strings):

0    2023-01-20
1    2023-04-27
2    2023-06-15
dtype: object

Tipo de datos: object

In [47]:

# Convertir a datetime usando pd.to_datetime()
my_series = pd.to_datetime(my_series)
print("Serie convertida a datetime:")
display(my_series)
print(f"Tipo de datos: {my_series.dtype}")
print()

Serie convertida a datetime:

0   2023-01-20
1   2023-04-27
2   2023-06-15
dtype: datetime64[ns]

Tipo de datos: datetime64[ns]

In [48]:

# Diferentes formatos de entrada
print("🔄 Conversión de diferentes formatos:")
formatos_diversos = pd.Series([
    '2024-03-15',
    '15/03/2024',
    '15-Mar-2024',
    'March 15, 2024',
    '2024-03-15 14:30:00'
])

print("Antes de la conversión:")
display(formatos_diversos)

🔄 Conversión de diferentes formatos:
Antes de la conversión:

0             2024-03-15
1             15/03/2024
2            15-Mar-2024
3         March 15, 2024
4    2024-03-15 14:30:00
dtype: object

In [49]:

# Pandas es inteligente y detecta automáticamente muchos formatos
fechas_convertidas = pd.to_datetime(formatos_diversos)
print("\nDespués de la conversión:")
print(fechas_convertidas)

ValueError: time data "15/03/2024" doesn't match format "%Y-%m-%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
# Pandas es inteligente y detecta automáticamente muchos formatos
fechas_convertidas = pd.to_datetime(formatos_diversos, format = "mixed")
print("\nDespués de la conversión:")
display(fechas_convertidas)

Después de la conversión:

0   2024-03-15 00:00:00
1   2024-03-15 00:00:00
2   2024-03-15 00:00:00
3   2024-03-15 00:00:00
4   2024-03-15 14:30:00
dtype: datetime64[ns]

In [51]:

# Para formatos específicos, usar el parámetro format
print("\n🎯 Conversión con formato específico:")
fechas_especificas = pd.Series(['15/03/2024', '20/06/2024', '31/12/2024'])
fechas_formato = pd.to_datetime(fechas_especificas, format='%d/%m/%Y')
display(fechas_formato)

🎯 Conversión con formato específico:

0   2024-03-15
1   2024-06-20
2   2024-12-31
dtype: datetime64[ns]

In [52]:

# Manejar errores en la conversión
print("\n⚠️ Manejo de errores:")
datos_mixtos = pd.Series(['2024-03-15', 'fecha_invalida', '2024-06-20', 'otro_error'])

# Con errors='coerce', valores inválidos se convierten en NaT (Not a Time)
fechas_con_errores = pd.to_datetime(datos_mixtos, errors='coerce')
print("Con errors='coerce':")
display(fechas_con_errores)

⚠️ Manejo de errores:
Con errors='coerce':

0   2024-03-15
1          NaT
2   2024-06-20
3          NaT
dtype: datetime64[ns]

In [53]:

# Crear DatetimeIndex
print("\n📊 Crear DatetimeIndex:")
rango_fechas = pd.date_range(start='2024-01-01', end='2024-01-10', freq='D')
print(f"Rango de fechas: {rango_fechas}")

# Crear DataFrame con índice de fechas
df_temporal = pd.DataFrame({
    'ventas': [100, 120, 95, 140, 110, 130, 105, 125, 115, 135],
    'visitas': [500, 550, 480, 600, 520, 580, 490, 570, 540, 590]
}, index=rango_fechas)

print("\nDataFrame con índice temporal:")
display(df_temporal)

📊 Crear DatetimeIndex:
Rango de fechas: DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D')

DataFrame con índice temporal:

            ventas  visitas
2024-01-01     100      500
2024-01-02     120      550
2024-01-03      95      480
2024-01-04     140      600
2024-01-05     110      520
2024-01-06     130      580
2024-01-07     105      490
2024-01-08     125      570
2024-01-09     115      540
2024-01-10     135      590

## 9. Accesor dt en Pandas Series {#9}

El accesor `dt` permite extraer componentes específicos de fechas en Series de Pandas:

In [54]:
# Crear serie de fechas para demostrar el accesor dt
fechas_ejemplo = pd.date_range('2024-01-01', '2024-12-31', freq='M')
serie_fechas = pd.Series(fechas_ejemplo)

print("Serie de fechas (mensuales):")
display(serie_fechas)

Serie de fechas (mensuales):

0    2024-01-31
1    2024-02-29
2    2024-03-31
3    2024-04-30
4    2024-05-31
5    2024-06-30
6    2024-07-31
7    2024-08-31
8    2024-09-30
9    2024-10-31
10   2024-11-30
11   2024-12-31
dtype: datetime64[ns]

In [55]:

# Ejemplos del documento
print("📅 Componentes básicos de fecha:")
print("Años:") 
display(serie_fechas.dt.year.head())
print("Meses :")
display(serie_fechas.dt.month.head())
print("Días: ")
display(serie_fechas.dt.day.head())

📅 Componentes básicos de fecha:
Años:

0    2024
1    2024
2    2024
3    2024
4    2024
dtype: int32

Meses :

0    1
1    2
2    3
3    4
4    5
dtype: int32

Días:

0    31
1    29
2    31
3    30
4    31
dtype: int32

In [56]:

# Más componentes útiles del accesor dt
print("🗓️ Componentes adicionales:")
print(f"Día de la semana (nombre): {serie_fechas.dt.day_name().head()}")
print(f"Día de la semana (número): {serie_fechas.dt.dayofweek.head()}")
print(f"Día del año: {serie_fechas.dt.dayofyear.head()}")
print(f"Nombre del mes: {serie_fechas.dt.month_name().head()}")
print(f"Trimestre: {serie_fechas.dt.quarter.head()}")
print(f"Semana del año: {serie_fechas.dt.isocalendar().week.head()}")
print()

🗓️ Componentes adicionales:
Día de la semana (nombre): 0    Wednesday
1     Thursday
2       Sunday
3      Tuesday
4       Friday
dtype: object
Día de la semana (número): 0    2
1    3
2    6
3    1
4    4
dtype: int32
Día del año: 0     31
1     60
2     91
3    121
4    152
dtype: int32
Nombre del mes: 0     January
1    February
2       March
3       April
4         May
dtype: object
Trimestre: 0    1
1    1
2    1
3    2
4    2
dtype: int32
Semana del año: 0     5
1     9
2    13
3    18
4    22
Name: week, dtype: UInt32

In [57]:

# 🌍 CAMBIAR IDIOMA - Diferentes opciones
print("🌍 Componentes en diferentes idiomas:")
print("=" * 50)

# OPCIÓN 1: Usar locale (configuración del sistema)
import locale
try:
    # Configurar locale en español
    # locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')  # Linux/Mac
    locale.setlocale(locale.LC_TIME, 'Spanish_Spain.1252')  # Windows
    
    # Usando strftime con locale
    fecha_ejemplo = serie_fechas.iloc[0]
    print(f"Con locale español:")
    print(f"  Día de la semana: {fecha_ejemplo.strftime('%A')}")
    print(f"  Mes: {fecha_ejemplo.strftime('%B')}")
    print()
except:
    print("No se pudo configurar el locale español")

🌍 Componentes en diferentes idiomas:
==================================================
Con locale español:
  Día de la semana: miércoles
  Mes: enero

In [59]:

# OPCIÓN 2: Diccionarios de traducción personalizados
print("📚 Usando diccionarios de traducción:")

# Diccionario de días en español
dias_espanol = {
    'Monday': 'Lunes',
    'Tuesday': 'Martes', 
    'Wednesday': 'Miércoles',
    'Thursday': 'Jueves',
    'Friday': 'Viernes',
    'Saturday': 'Sábado',
    'Sunday': 'Domingo'
}

# Diccionario de meses en español
meses_espanol = {
    'January': 'que calor',
    'February': 'Febrero',
    'March': 'Marzo',
    'April': 'Abril',
    'May': 'Mayo',
    'June': 'Junio',
    'July': 'Julio',
    'August': 'Agosto',
    'September': 'Septiembre',
    'October': 'Octubre',
    'November': 'Noviembre',
    'December': 'Diciembre'
}

# Aplicar traducción
dias_en_espanol  = serie_fechas.dt.day_name().map(dias_espanol)
meses_en_espanol = serie_fechas.dt.month_name().map(meses_espanol)

print("Días de la semana en español:")
print(dias_en_espanol.head())
print("\nMeses en español:")
print(meses_en_espanol.head())
print()

📚 Usando diccionarios de traducción:
Días de la semana en español:
0    Miércoles
1       Jueves
2      Domingo
3       Martes
4      Viernes
dtype: object

Meses en español:
0    que calor
1      Febrero
2        Marzo
3        Abril
4         Mayo
dtype: object

In [60]:

# OPCIÓN 3: Múltiples idiomas
print("🌐 Componentes en múltiples idiomas:")

# Francés
dias_frances = {
    'Monday': 'Lundi', 'Tuesday': 'Mardi', 'Wednesday': 'Mercredi',
    'Thursday': 'Jeudi', 'Friday': 'Vendredi', 'Saturday': 'Samedi', 'Sunday': 'Dimanche'
}

meses_frances = {
    'January': 'Janvier', 'February': 'Février', 'March': 'Mars', 'April': 'Avril',
    'May': 'Mai', 'June': 'Juin', 'July': 'Juillet', 'August': 'Août',
    'September': 'Septembre', 'October': 'Octobre', 'November': 'Novembre', 'December': 'Décembre'
}

# Italiano
dias_italiano = {
    'Monday': 'Lunedì', 'Tuesday': 'Martedì', 'Wednesday': 'Mercoledì',
    'Thursday': 'Giovedì', 'Friday': 'Venerdì', 'Saturday': 'Sabato', 'Sunday': 'Domenica'
}

meses_italiano = {
    'January': 'Gennaio', 'February': 'Febbraio', 'March': 'Marzo', 'April': 'Aprile',
    'May': 'Maggio', 'June': 'Giugno', 'July': 'Luglio', 'August': 'Agosto',
    'September': 'Settembre', 'October': 'Ottobre', 'November': 'Novembre', 'December': 'Dicembre'
}

# Portugués
dias_portugues = {
    'Monday': 'Segunda-feira', 'Tuesday': 'Terça-feira', 'Wednesday': 'Quarta-feira',
    'Thursday': 'Quinta-feira', 'Friday': 'Sexta-feira', 'Saturday': 'Sábado', 'Sunday': 'Domingo'
}

meses_portugues = {
    'January': 'Janeiro', 'February': 'Fevereiro', 'March': 'Março', 'April': 'Abril',
    'May': 'Maio', 'June': 'Junho', 'July': 'Julho', 'August': 'Agosto',
    'September': 'Setembro', 'October': 'Outubro', 'November': 'Novembro', 'December': 'Dezembro'
}

# Mostrar ejemplos
fecha_muestra = serie_fechas.iloc[0]
dia_ingles = fecha_muestra.day_name()
mes_ingles = fecha_muestra.month_name()

print(f"Fecha ejemplo: {fecha_muestra.strftime('%Y-%m-%d')}")
print(f"Inglés:    {dia_ingles}, {mes_ingles}")
print(f"Español:   {dias_espanol[dia_ingles]}, {meses_espanol[mes_ingles]}")
print(f"Francés:   {dias_frances[dia_ingles]}, {meses_frances[mes_ingles]}")
print(f"Italiano:  {dias_italiano[dia_ingles]}, {meses_italiano[mes_ingles]}")
print(f"Portugués: {dias_portugues[dia_ingles]}, {meses_portugues[mes_ingles]}")
print()

🌐 Componentes en múltiples idiomas:
Fecha ejemplo: 2024-01-31
Inglés:    Wednesday, January
Español:   Miércoles, que calor
Francés:   Mercredi, Janvier
Italiano:  Mercoledì, Gennaio
Portugués: Quarta-feira, Janeiro

In [61]:

# OPCIÓN 4: Función para crear DataFrame multiidioma
def crear_df_multiidioma(fechas_serie):
    """Crea un DataFrame con componentes de fecha en múltiples idiomas"""
    
    df_multi = pd.DataFrame({
        'fecha': fechas_serie,
        'dia_numero': fechas_serie.dt.day,
        'mes_numero': fechas_serie.dt.month,
        'año': fechas_serie.dt.year,
        
        # Inglés (original)
        'dia_en': fechas_serie.dt.day_name(),
        'mes_en': fechas_serie.dt.month_name(),
        
        # Español
        'dia_es': fechas_serie.dt.day_name().map(dias_espanol),
        'mes_es': fechas_serie.dt.month_name().map(meses_espanol),
        
        # Francés
        'dia_fr': fechas_serie.dt.day_name().map(dias_frances),
        'mes_fr': fechas_serie.dt.month_name().map(meses_frances),
        
        # Italiano
        'dia_it': fechas_serie.dt.day_name().map(dias_italiano),
        'mes_it': fechas_serie.dt.month_name().map(meses_italiano)
    })
    
    return df_multi

In [62]:

print("📊 DataFrame con múltiples idiomas:")
df_multiidioma = crear_df_multiidioma(serie_fechas)
display(df_multiidioma.head())

# OPCIÓN 5: Usando babel para localización avanzada
print("\n🔧 Ejemplo con configuración de sistema (Windows):")
print("Para Windows, puedes usar estos códigos de locale:")
print("  - Español: 'Spanish_Spain.1252' o 'es_ES'")
print("  - Francés: 'French_France.1252' o 'fr_FR'")
print("  - Italiano: 'Italian_Italy.1252' o 'it_IT'")
print("  - Portugués: 'Portuguese_Brazil.1252' o 'pt_BR'")

# Ejemplo de uso práctico
print("\n💡 Ejemplo práctico - Reporte en español:")
fecha_hoy = pd.Timestamp.now()
dia_hoy = dias_espanol.get(fecha_hoy.day_name(), fecha_hoy.day_name())
mes_hoy = meses_espanol.get(fecha_hoy.month_name(), fecha_hoy.month_name())

print(f"Reporte generado el {dia_hoy}, {fecha_hoy.day} de {mes_hoy} de {fecha_hoy.year}")

📊 DataFrame con múltiples idiomas:

,fecha,dia_numero,mes_numero,año,dia_en,mes_en,dia_es,mes_es,dia_fr,mes_fr,dia_it,mes_it
0,2024-01-31,31,1,2024,Wednesday,January,Miércoles,que calor,Mercredi,Janvier,Mercoledì,Gennaio
1,2024-02-29,29,2,2024,Thursday,February,Jueves,Febrero,Jeudi,Février,Giovedì,Febbraio
2,2024-03-31,31,3,2024,Sunday,March,Domingo,Marzo,Dimanche,Mars,Domenica,Marzo
3,2024-04-30,30,4,2024,Tuesday,April,Martes,Abril,Mardi,Avril,Martedì,Aprile
4,2024-05-31,31,5,2024,Friday,May,Viernes,Mayo,Vendredi,Mai,Venerdì,Maggio

🔧 Ejemplo con configuración de sistema (Windows):
Para Windows, puedes usar estos códigos de locale:
  - Español: 'Spanish_Spain.1252' o 'es_ES'
  - Francés: 'French_France.1252' o 'fr_FR'
  - Italiano: 'Italian_Italy.1252' o 'it_IT'
  - Portugués: 'Portuguese_Brazil.1252' o 'pt_BR'

💡 Ejemplo práctico - Reporte en español:
Reporte generado el Sábado, 4 de Octubre de 2025

In [65]:

# Componentes de tiempo
fechas_con_hora = pd.Series(pd.date_range('2024-01-01 08:30:45', periods=5, freq='3H'))
print("⏰ Componentes de tiempo:")
print(f"Fechas con hora: {fechas_con_hora}")
print(f"Horas: {fechas_con_hora.dt.hour}")
print(f"Minutos: {fechas_con_hora.dt.minute}")
print(f"Segundos: {fechas_con_hora.dt.second}")
print()

⏰ Componentes de tiempo:
Fechas con hora: 0   2024-01-01 08:30:45
1   2024-01-01 11:30:45
2   2024-01-01 14:30:45
3   2024-01-01 17:30:45
4   2024-01-01 20:30:45
dtype: datetime64[ns]
Horas: 0     8
1    11
2    14
3    17
4    20
dtype: int32
Minutos: 0    30
1    30
2    30
3    30
4    30
dtype: int32
Segundos: 0    45
1    45
2    45
3    45
4    45
dtype: int32

In [66]:

# Propiedades booleanas útiles
print("✅ Propiedades booleanas:")
print(f"¿Es inicio de mes?: {serie_fechas.dt.is_month_start.head()}")
print(f"¿Es fin de mes?: {serie_fechas.dt.is_month_end.head()}")
print(f"¿Es año bisiesto?: {serie_fechas.dt.is_leap_year.head()}")

# Crear DataFrame con componentes extraídos
df_componentes = pd.DataFrame({
    'fecha_original': serie_fechas.head(6),
    'año': serie_fechas.dt.year.head(6),
    'mes': serie_fechas.dt.month.head(6),
    'mes_nombre': serie_fechas.dt.month_name().head(6),
    'dia_semana': serie_fechas.dt.day_name().head(6),
    'trimestre': serie_fechas.dt.quarter.head(6)
})

print("\n📊 DataFrame con componentes extraídos:")
print(df_componentes)

✅ Propiedades booleanas:
¿Es inicio de mes?: 0    False
1    False
2    False
3    False
4    False
dtype: bool
¿Es fin de mes?: 0    True
1    True
2    True
3    True
4    True
dtype: bool
¿Es año bisiesto?: 0    True
1    True
2    True
3    True
4    True
dtype: bool

📊 DataFrame con componentes extraídos:
  fecha_original   año  mes mes_nombre dia_semana  trimestre
0     2024-01-31  2024    1    January  Wednesday          1
1     2024-02-29  2024    2   February   Thursday          1
2     2024-03-31  2024    3      March     Sunday          1
3     2024-04-30  2024    4      April    Tuesday          2
4     2024-05-31  2024    5        May     Friday          2
5     2024-06-30  2024    6       June     Sunday          2

## 10. Operaciones Avanzadas con Fechas en Pandas {#10}

Pandas permite realizar operaciones aritméticas y crear rangos de fechas sofisticados:

In [67]:
# Aritmética de fechas con Pandas
fecha_base = pd.Timestamp('2024-01-15')
print(f"Fecha base: {fecha_base}")

# Sumar diferentes períodos
print("\n➕ Suma de períodos:")
print(f"+ 30 días: {fecha_base   + pd.Timedelta(days=30)}")
print(f"+ 2 semanas: {fecha_base + pd.Timedelta(weeks=2)}")
print(f"+ 3 meses: {fecha_base   + pd.DateOffset(months=3)}")
print(f"+ 1 año: {fecha_base     + pd.DateOffset(years=1)}")

Fecha base: 2024-01-15 00:00:00

➕ Suma de períodos:
+ 30 días: 2024-02-14 00:00:00
+ 2 semanas: 2024-01-29 00:00:00
+ 3 meses: 2024-04-15 00:00:00
+ 1 año: 2025-01-15 00:00:00

In [70]:

# Crear rangos de fechas con diferentes frecuencias
print("\n📅 Rangos de fechas con diferentes frecuencias:")

frecuencias = {
    'D': 'Diario',
    'W': 'Semanal',
    'M': 'Mensual',
    'Q': 'Trimestral',
    'Y': 'Anual',
    'B': 'Días laborables',
    'H': 'Cada hora',
    '2D': 'Cada 2 días'
}

for freq, descripcion in frecuencias.items():
    if freq in ['H']:  # Para frecuencias altas, limitamos los períodos
        rango = pd.date_range('2024-01-01', periods=5, freq=freq)
    else:
        rango = pd.date_range('2024-01-01', periods=4, freq=freq)
    print(f"{descripcion:15} ({freq:^3}): {rango[0]} ... {rango[-1]} ({len(rango)} períodos)")

📅 Rangos de fechas con diferentes frecuencias:
Diario          ( D ): 2024-01-01 00:00:00 ... 2024-01-04 00:00:00 (4 períodos)
Semanal         ( W ): 2024-01-07 00:00:00 ... 2024-01-28 00:00:00 (4 períodos)
Mensual         ( M ): 2024-01-31 00:00:00 ... 2024-04-30 00:00:00 (4 períodos)
Trimestral      ( Q ): 2024-03-31 00:00:00 ... 2024-12-31 00:00:00 (4 períodos)
Anual           ( Y ): 2024-12-31 00:00:00 ... 2027-12-31 00:00:00 (4 períodos)
Días laborables ( B ): 2024-01-01 00:00:00 ... 2024-01-04 00:00:00 (4 períodos)
Cada hora       ( H ): 2024-01-01 00:00:00 ... 2024-01-01 04:00:00 (5 períodos)
Cada 2 días     (2D ): 2024-01-01 00:00:00 ... 2024-01-07 00:00:00 (4 períodos)

In [68]:

# Cálculo de diferencias temporales
print("\n⏱️ Cálculo de diferencias temporales:")
fechas_inicio = pd.Series(['2024-01-01', '2024-02-15', '2024-03-30'])
fechas_fin = pd.Series(['2024-01-31', '2024-03-01', '2024-04-15'])

fechas_inicio = pd.to_datetime(fechas_inicio)
fechas_fin = pd.to_datetime(fechas_fin)

diferencias = fechas_fin - fechas_inicio
print("Diferencias:")
for i, diff in enumerate(diferencias):
    print(f"Período {i+1}: {diff} ({diff.days} días)")

⏱️ Cálculo de diferencias temporales:
Diferencias:
Período 1: 30 days 00:00:00 (30 días)
Período 2: 15 days 00:00:00 (15 días)
Período 3: 16 days 00:00:00 (16 días)

In [69]:

# Operaciones útiles con BusinessDay
print("\n💼 Trabajar con días laborables:")
fecha_inicio = pd.Timestamp('2024-01-01')  # Lunes
print(f"Fecha inicio: {fecha_inicio.strftime('%A, %d/%m/%Y')}")

💼 Trabajar con días laborables:
Fecha inicio: lunes, 01/01/2024

In [71]:
from pandas.tseries.offsets import BDay

In [72]:

# Agregar días laborables
proximo_laboral = fecha_inicio + BDay(1)
print(f"Siguiente día laboral: {proximo_laboral.strftime('%A, %d/%m/%Y')}")

Siguiente día laboral: martes, 02/01/2024

In [77]:

# Agregar 5 días laborables (1 semana laboral)
semana_laboral = fecha_inicio + BDay(5)
print(f"Después de 1 semana laboral: {semana_laboral.strftime('%A, %d/%m/%Y')}")

Después de 1 semana laboral: lunes, 08/01/2024

In [79]:

# Crear DataFrame con análisis temporal
print("\n📊 DataFrame con análisis temporal:")
rango_datos = pd.date_range('2024-01-01', '2024-03-31', freq='D')
np.random.seed(42)
ventas = np.random.randint(50, 200, len(rango_datos))

df_ventas = pd.DataFrame({
    'fecha': rango_datos,
    'ventas': ventas
})

# Agregar columnas derivadas
df_ventas['año'] = df_ventas['fecha'].dt.year
df_ventas['mes'] = df_ventas['fecha'].dt.month
df_ventas['dia_semana'] = df_ventas['fecha'].dt.day_name(locale = 'es_ES')
df_ventas['es_fin_semana'] = df_ventas['fecha'].dt.dayofweek >= 5
df_ventas['trimestre'] = df_ventas['fecha'].dt.quarter

print(df_ventas.head(10))

📊 DataFrame con análisis temporal:
       fecha  ventas   año  mes dia_semana  es_fin_semana  trimestre
0 2024-01-01     152  2024    1      Lunes          False          1
1 2024-01-02     142  2024    1     Martes          False          1
2 2024-01-03      64  2024    1  Miércoles          False          1
3 2024-01-04     156  2024    1     Jueves          False          1
4 2024-01-05     121  2024    1    Viernes          False          1
5 2024-01-06      70  2024    1     Sábado           True          1
6 2024-01-07     152  2024    1    Domingo           True          1
7 2024-01-08     171  2024    1      Lunes          False          1
8 2024-01-09     124  2024    1     Martes          False          1
9 2024-01-10     137  2024    1  Miércoles          False          1

## 11. Filtrado y Selección por Fechas {#11}

Pandas facilita el filtrado de datos por fechas y rangos temporales:

In [87]:
# Crear DataFrame con índice temporal para demostrar filtrado
fechas_completas = pd.date_range('2024-01-01', '2024-12-31', freq='D')
np.random.seed(42)
datos_ejemplo = pd.DataFrame({
    'ventas': np.random.randint(100, 1000, len(fechas_completas)),
    'clientes': np.random.randint(20, 100, len(fechas_completas)),
    'temperatura': np.random.normal(20, 10, len(fechas_completas))
}, index=fechas_completas)

print("DataFrame original (primeros 5 registros):")
print(datos_ejemplo.head())
print(f"\nForma del DataFrame: {datos_ejemplo.shape}")
print()

DataFrame original (primeros 5 registros):
            ventas  clientes  temperatura
2024-01-01     202        44     6.797668
2024-01-02     535        37    38.314588
2024-01-03     960        85    31.794401
2024-01-04     370        73    15.308243
2024-01-05     206        54     2.868655

Forma del DataFrame: (366, 3)

In [88]:

# Filtrado por fechas específicas
print("🎯 Filtrado por fechas específicas:")

# Filtrar un día específico
dia_especifico = datos_ejemplo.loc['2024-06-15']
print(f"Datos del 15 de junio: {dia_especifico}")

🎯 Filtrado por fechas específicas:
Datos del 15 de junio: ventas         317.000000
clientes        88.000000
temperatura     23.944521
Name: 2024-06-15 00:00:00, dtype: float64

In [89]:

# Filtrar un mes completo
enero = datos_ejemplo.loc['2024-01']
print(f"Datos de enero (primeros 5): ")
print(enero.head())
print(f"Total de registros en enero: {len(enero)}")

Datos de enero (primeros 5):
            ventas  clientes  temperatura
2024-01-01     202        44     6.797668
2024-01-02     535        37    38.314588
2024-01-03     960        85    31.794401
2024-01-04     370        73    15.308243
2024-01-05     206        54     2.868655
Total de registros en enero: 31

In [90]:

# Filtrar un rango de fechas
print("\n📊 Filtrado por rangos:")
primer_trimestre = datos_ejemplo.loc['2024-01-01':'2024-03-31']
print(f"Primer trimestre: {len(primer_trimestre)} registros")

📊 Filtrado por rangos:
Primer trimestre: 91 registros

In [92]:

# Filtrado usando condiciones
print("\n🔍 Filtrado con condiciones:")

# Filtrar días con ventas altas
ventas_altas = datos_ejemplo[datos_ejemplo['ventas'] > 800]
print(f"Días con ventas > 800: {len(ventas_altas)}")

🔍 Filtrado con condiciones:
Días con ventas > 800: 82

In [97]:

# Filtrar por día de la semana
datos_ejemplo['dia_semana'] = datos_ejemplo.index.day_name(locale = 'es_ES')
display(datos_ejemplo.sample(10))
fines_semana = datos_ejemplo[datos_ejemplo['dia_semana'].isin(['Sábado', 'Domingo'])]
print(f"Registros de fines de semana: {len(fines_semana)}")

            ventas  clientes  temperatura dia_semana
2024-11-07     246        44     5.915387     Jueves
2024-02-05     847        88    26.860515      Lunes
2024-07-10     848        84    42.706929  Miércoles
2024-02-27     120        37     9.407865     Martes
2024-03-03     700        65    14.697424    Domingo
2024-03-01     373        77    10.142740    Viernes
2024-10-21     297        58    17.596746      Lunes
2024-08-28     763        28    18.419921  Miércoles
2024-07-16     259        48    11.439162     Martes
2024-03-15     527        67    26.141667    Viernes

Registros de fines de semana: 104

In [98]:

# Filtrar por mes específico
mayo_datos = datos_ejemplo[datos_ejemplo.index.month == 5]
print(f"Registros de mayo: {len(mayo_datos)}")

Registros de mayo: 31

In [99]:

# Combinando condiciones
print("\n🎭 Filtros combinados:")
verano_ventas_altas = datos_ejemplo[
    (datos_ejemplo.index.month.isin([12, 1, 2])) &  # Meses de verano
    (datos_ejemplo['ventas'] > 700)  # Ventas altas
]
print(f"Ventas altas en verano: {len(verano_ventas_altas)} registros")

# Selección con .between()
print("\n📅 Usando between() para rangos:")
rango_especifico = datos_ejemplo[
    datos_ejemplo.index.to_series().between('2024-06-01', '2024-08-31')
]
print(f"Datos entre junio y agosto: {len(rango_especifico)} registros")

🎭 Filtros combinados:
Ventas altas en verano: 27 registros

📅 Usando between() para rangos:
Datos entre junio y agosto: 92 registros

In [100]:

# Filtrado por trimestre
print("\n📈 Filtrado por trimestre:")
datos_ejemplo['trimestre'] = datos_ejemplo.index.quarter
for trim in [1, 2, 3, 4]:
    trim_datos = datos_ejemplo[datos_ejemplo['trimestre'] == trim]
    promedio_ventas = trim_datos['ventas'].mean()
    print(f"Q{trim}: {len(trim_datos)} registros, promedio ventas: {promedio_ventas:.0f}")

📈 Filtrado por trimestre:
Q1: 91 registros, promedio ventas: 535
Q2: 91 registros, promedio ventas: 579
Q3: 92 registros, promedio ventas: 579
Q4: 92 registros, promedio ventas: 538

In [103]:

# Mostrar estadísticas por período
print("\n📊 Resumen estadístico por mes:")
resumen_mensual = datos_ejemplo.groupby(datos_ejemplo.index.month).agg({
    'ventas': ['mean', 'max', 'min'],
    'clientes': 'mean'
}).round(0)

resumen_mensual

📊 Resumen estadístico por mes:

   ventas           clientes
     mean  max  min     mean
1   480.0  971  120     57.0
2   598.0  975  120     59.0
3   530.0  997  101     54.0
4   555.0  978  114     64.0
5   507.0  956  127     55.0
6   677.0  991  104     58.0
7   592.0  999  127     59.0
8   587.0  926  289     57.0
9   556.0  954  101     57.0
10  530.0  983  152     59.0
11  632.0  980  243     59.0
12  456.0  996  101     58.0

In [104]:

resumen_mensual.columns = ['Ventas_Promedio', 'Ventas_Max', 'Ventas_Min', 'Clientes_Promedio']

In [105]:
resumen_mensual

    Ventas_Promedio  Ventas_Max  Ventas_Min  Clientes_Promedio
1             480.0         971         120               57.0
2             598.0         975         120               59.0
3             530.0         997         101               54.0
4             555.0         978         114               64.0
5             507.0         956         127               55.0
6             677.0         991         104               58.0
7             592.0         999         127               59.0
8             587.0         926         289               57.0
9             556.0         954         101               57.0
10            530.0         983         152               59.0
11            632.0         980         243               59.0
12            456.0         996         101               58.0

## 12. Resampleo y Agrupación Temporal {#12}

El resampleo permite cambiar la frecuencia temporal de los datos y realizar agregaciones:

In [106]:
# Usar el DataFrame creado anteriormente para demostrar resampleo
print("📊 Resampleo de datos temporales:")
print(f"Datos originales: {len(datos_ejemplo)} registros diarios")
print()

📊 Resampleo de datos temporales:
Datos originales: 366 registros diarios

In [107]:

# Resampleo a frecuencias mayores (agregación)
print("🔼 Agregación a frecuencias mayores:")

# Resampleo mensual
mensual = datos_ejemplo.resample('M').agg({
    'ventas': 'sum',
    'clientes': 'mean',
    'temperatura': 'mean'
}).round(2)

print("Resampleo mensual (primeros 6 meses):")
print(mensual.head(6))
print()

🔼 Agregación a frecuencias mayores:
Resampleo mensual (primeros 6 meses):
            ventas  clientes  temperatura
2024-01-31   14891     57.35        21.56
2024-02-29   17347     58.55        18.48
2024-03-31   16439     53.68        19.30
2024-04-30   16648     63.90        18.91
2024-05-31   15715     55.19        17.29
2024-06-30   20298     57.73        19.15

In [108]:

# Resampleo semanal
semanal = datos_ejemplo.resample('W').agg({
    'ventas': ['sum', 'mean'],
    'clientes': 'mean'
}).round(0)

semanal.columns = ['Ventas_Total', 'Ventas_Promedio', 'Clientes_Promedio']
print("Resampleo semanal (primeras 4 semanas):")
print(semanal.head(4))
print()

Resampleo semanal (primeras 4 semanas):
            Ventas_Total  Ventas_Promedio  Clientes_Promedio
2024-01-07          3244            463.0               67.0
2024-01-14          2923            418.0               56.0
2024-01-21          3583            512.0               48.0
2024-01-28          4214            602.0               66.0

In [109]:

# Resampleo trimestral
trimestral = datos_ejemplo.resample('Q').agg({
    'ventas': ['sum', 'mean', 'std'],
    'clientes': ['mean', 'max'],
    'temperatura': ['mean', 'min', 'max']
}).round(2)

print("Resampleo trimestral:")
print(trimestral)
print()

Resampleo trimestral:
           ventas                 clientes     temperatura
              sum    mean     std     mean max        mean   min    max
2024-03-31  48677  534.91  264.72    56.48  99       19.81 -3.02  50.79
2024-06-30  52661  578.69  277.17    58.90  99       18.44 -4.72  40.75
2024-09-30  53242  578.72  234.16    57.43  97       20.48 -6.97  45.73
2024-12-31  49528  538.35  261.85    58.77  99       19.05 -6.51  46.32

In [111]:

# Diferentes tipos de agregación
print("🎯 Diferentes métodos de agregación:")

agregaciones_avanzadas = datos_ejemplo.resample('M').agg({
    'ventas': ['sum', 'mean', 'median', 'std', 'min', 'max'],
    'clientes': ['mean', 'sum', 'count']
})

print("Agregaciones múltiples (primeros 3 meses):")
display(agregaciones_avanzadas.head(3))
print()

# Resampleo con función personalizada
print("🔧 Función de agregación personalizada:")

def rango_ventas(series):
    return series.max() - series.min()

custom_resample = datos_ejemplo.resample('M').agg({
    'ventas': [rango_ventas, 'mean'],
    'clientes': 'mean'
})

custom_resample.columns = ['Rango_Ventas', 'Ventas_Promedio', 'Clientes_Promedio']
print("Resampleo con función personalizada (primeros 6 meses):")
print(custom_resample.head(6))
print()

🎯 Diferentes métodos de agregación:
Agregaciones múltiples (primeros 3 meses):

           ventas                                            clientes        \
              sum        mean median         std  min  max       mean   sum
2024-01-31  14891  480.354839  443.0  255.936913  120  971  57.354839  1778
2024-02-29  17347  598.172414  610.0  269.948020  120  975  58.551724  1698
2024-03-31  16439  530.290323  489.0  264.100637  101  997  53.677419  1664


           count
2024-01-31    31
2024-02-29    29
2024-03-31    31

🔧 Función de agregación personalizada:
Resampleo con función personalizada (primeros 6 meses):
            Rango_Ventas  Ventas_Promedio  Clientes_Promedio
2024-01-31           851       480.354839          57.354839
2024-02-29           855       598.172414          58.551724
2024-03-31           896       530.290323          53.677419
2024-04-30           864       554.933333          63.900000
2024-05-31           829       506.935484          55.193548
2024-06-30           887       676.600000          57.733333

In [113]:

# Análisis de tendencias temporales
print("📈 Análisis de tendencias:")

# Calcular medias móviles
datos_ejemplo['ventas_ma_7d'] = datos_ejemplo['ventas'].rolling(window=7).mean()
datos_ejemplo['ventas_ma_30d'] = datos_ejemplo['ventas'].rolling(window=30).mean()

# Mostrar los datos con medias móviles
print("Datos con medias móviles (últimos 10 registros):")
display(datos_ejemplo[['ventas', 'ventas_ma_7d', 'ventas_ma_30d']].tail(10).round(2))
print()

📈 Análisis de tendencias:
Datos con medias móviles (últimos 10 registros):

            ventas  ventas_ma_7d  ventas_ma_30d
2024-12-22     686        473.00         490.23
2024-12-23     724        504.57         490.70
2024-12-24     519        542.86         495.93
2024-12-25     521        595.43         484.53
2024-12-26     203        593.14         483.20
2024-12-27     951        618.71         500.07
2024-12-28     353        565.29         487.73
2024-12-29     326        513.86         476.23
2024-12-30     211        440.57         450.60
2024-12-31     609        453.43         467.53

In [114]:

# Comparación año a año (simulado)
print("📅 Análisis temporal avanzado:")

# Agregar información temporal adicional
datos_ejemplo['mes'] = datos_ejemplo.index.month
datos_ejemplo['dia_año'] = datos_ejemplo.index.dayofyear
datos_ejemplo['semana_año'] = datos_ejemplo.index.isocalendar().week

# Estadísticas por día de la semana
por_dia_semana = datos_ejemplo.groupby(datos_ejemplo['dia_semana']).agg({
    'ventas': ['mean', 'std'],
    'clientes': 'mean'
}).round(2)

por_dia_semana.columns = ['Ventas_Promedio', 'Ventas_StdDev', 'Clientes_Promedio']
print("Estadísticas por día de la semana:")
display(por_dia_semana)

📅 Análisis temporal avanzado:
Estadísticas por día de la semana:

            Ventas_Promedio  Ventas_StdDev  Clientes_Promedio
dia_semana
Domingo              598.56         286.84              56.15
Jueves               576.60         251.15              58.54
Lunes                564.30         246.41              56.06
Martes               480.92         225.64              57.11
Miércoles            588.37         280.89              60.33
Sábado               550.65         254.87              60.63
Viernes              545.65         264.89              56.52

In [115]:

# Resampleo con diferentes anclas (label)
print("\n⚓ Resampleo con diferentes etiquetas:")
resample_left = datos_ejemplo.resample('M', label='left').sum()['ventas'].head(3)
resample_right = datos_ejemplo.resample('M', label='right').sum()['ventas'].head(3)

print("Label='left':")
display(resample_left)
print("\nLabel='right':")
display(resample_right)

⚓ Resampleo con diferentes etiquetas:
Label='left':

2023-12-31    14891
2024-01-31    17347
2024-02-29    16439
Freq: ME, Name: ventas, dtype: int32

Label='right':

2024-01-31    14891
2024-02-29    17347
2024-03-31    16439
Freq: ME, Name: ventas, dtype: int32

In [116]:
# Resampleo con diferentes anclas (label) - EXPLICACIÓN DETALLADA
print("\n⚓ Resampleo con diferentes etiquetas:")
print("🔍 ¿Qué significa 'label' en resample?")
print("=" * 50)

# Crear datos de ejemplo para entender mejor
fechas_ejemplo = pd.date_range('2024-01-01', '2024-03-15', freq='D')
ventas_ejemplo = np.random.randint(100, 200, len(fechas_ejemplo))
df_ejemplo = pd.DataFrame({'ventas': ventas_ejemplo}, index=fechas_ejemplo)

print("📊 Datos originales (primeros 10 días):")
display(df_ejemplo.head(10))

print("\n🏷️ LABEL='LEFT' vs LABEL='RIGHT':")
print("=" * 40)

# Resampleo mensual con label='left' (por defecto)
resample_left = df_ejemplo.resample('M', label='left').sum()['ventas']
print("📅 Label='left' (etiqueta al INICIO del período):")
display(resample_left)

# Resampleo mensual con label='right' 
resample_right = df_ejemplo.resample('M', label='right').sum()['ventas']
print("\n📅 Label='right' (etiqueta al FINAL del período):")
display(resample_right)

print("\n💡 EXPLICACIÓN:")
print("─" * 30)
print("• Label='left':  Etiqueta usa la fecha del INICIO del período")
print("  Enero se etiqueta como: 2024-01-01")
print("  Febrero se etiqueta como: 2024-02-01")
print()
print("• Label='right': Etiqueta usa la fecha del FINAL del período") 
print("  Enero se etiqueta como: 2024-01-31")
print("  Febrero se etiqueta como: 2024-02-29")
print()
print("⚠️  LOS DATOS SON LOS MISMOS, solo cambia la ETIQUETA")

# Demostrar que los valores son iguales
print(f"\n🔢 Verificación - valores son iguales:")
print(f"Enero - Left: {resample_left.iloc[0]:,}")
print(f"Enero - Right: {resample_right.iloc[0]:,}")
print(f"¿Son iguales? {resample_left.iloc[0] == resample_right.iloc[0]}")

print("\n🎯 CASOS DE USO:")
print("─" * 20)
print("📈 Label='left' (más común):")
print("  → Para reportes que se refieren al inicio del período")
print("  → 'Ventas de enero' → etiquetado como 2024-01-01")
print()
print("📊 Label='right':")
print("  → Para reportes de cierre de período")
print("  → 'Ventas hasta enero' → etiquetado como 2024-01-31")

# Ejemplo práctico con trimestres
print("\n🗓️ EJEMPLO PRÁCTICO - Trimestres:")
print("─" * 35)
trim_left = df_ejemplo.resample('Q', label='left').sum()['ventas']
trim_right = df_ejemplo.resample('Q', label='right').sum()['ventas']

print("Trimestral con label='left':")
display(trim_left)
print("\nTrimestral con label='right':")
display(trim_right)

print("\n💼 EN RESUMEN:")
print("═" * 25)
print("• Los DATOS son idénticos")
print("• Solo cambia la FECHA de la etiqueta")
print("• 'left' = inicio del período") 
print("• 'right' = final del período")
print("• Por defecto pandas usa 'left'")
print("• Útil para diferentes tipos de reportes")

⚓ Resampleo con diferentes etiquetas:
🔍 ¿Qué significa 'label' en resample?
==================================================
📊 Datos originales (primeros 10 días):

            ventas
2024-01-01     127
2024-01-02     192
2024-01-03     125
2024-01-04     124
2024-01-05     111
2024-01-06     104
2024-01-07     197
2024-01-08     147
2024-01-09     136
2024-01-10     178

🏷️ LABEL='LEFT' vs LABEL='RIGHT':
========================================
📅 Label='left' (etiqueta al INICIO del período):

2023-12-31    4493
2024-01-31    4156
2024-02-29    2201
Freq: ME, Name: ventas, dtype: int32

📅 Label='right' (etiqueta al FINAL del período):

2024-01-31    4493
2024-02-29    4156
2024-03-31    2201
Freq: ME, Name: ventas, dtype: int32

💡 EXPLICACIÓN:
──────────────────────────────
• Label='left':  Etiqueta usa la fecha del INICIO del período
  Enero se etiqueta como: 2024-01-01
  Febrero se etiqueta como: 2024-02-01

• Label='right': Etiqueta usa la fecha del FINAL del período
  Enero se etiqueta como: 2024-01-31
  Febrero se etiqueta como: 2024-02-29

⚠️  LOS DATOS SON LOS MISMOS, solo cambia la ETIQUETA

🔢 Verificación - valores son iguales:
Enero - Left: 4,493
Enero - Right: 4,493
¿Son iguales? True

🎯 CASOS DE USO:
────────────────────
📈 Label='left' (más común):
  → Para reportes que se refieren al inicio del período
  → 'Ventas de enero' → etiquetado como 2024-01-01

📊 Label='right':
  → Para reportes de cierre de período
  → 'Ventas hasta enero' → etiquetado como 2024-01-31

🗓️ EJEMPLO PRÁCTICO - Trimestres:
───────────────────────────────────
Trimestral con label='left':

2023-12-31    10850
Freq: QE-DEC, Name: ventas, dtype: int32

Trimestral con label='right':

2024-03-31    10850
Freq: QE-DEC, Name: ventas, dtype: int32

💼 EN RESUMEN:
═════════════════════════
• Los DATOS son idénticos
• Solo cambia la FECHA de la etiqueta
• 'left' = inicio del período
• 'right' = final del período
• Por defecto pandas usa 'left'
• Útil para diferentes tipos de reportes

In [117]:
# DEMOSTRACIÓN: Los datos son IDÉNTICOS
print("🔍 CONFIRMACIÓN: Los resultados son exactamente iguales")
print("=" * 60)

# Crear datos simples para ver mejor
fechas_test = pd.date_range('2024-01-01', '2024-02-15', freq='D')
ventas_test = [100, 150, 200, 120, 180] * (len(fechas_test) // 5 + 1)
ventas_test = ventas_test[:len(fechas_test)]  # Ajustar longitud

df_test = pd.DataFrame({'ventas': ventas_test}, index=fechas_test)

# Resampleo mensual con ambas etiquetas
enero_left = df_test.resample('M', label='left').sum()['ventas']
enero_right = df_test.resample('M', label='right').sum()['ventas']

print("📊 DATOS DE ENERO:")
print(f"Label='left':  {enero_left.iloc[0]:,} ventas")
print(f"Label='right': {enero_right.iloc[0]:,} ventas")
print(f"¿Son iguales? {enero_left.iloc[0] == enero_right.iloc[0]} ✅")

print("\n📅 DIFERENCIA: Solo las etiquetas de tiempo")
print(f"Label='left':  etiqueta = {enero_left.index[0].strftime('%Y-%m-%d')}")
print(f"Label='right': etiqueta = {enero_right.index[0].strftime('%Y-%m-%d')}")

print("\n💡 CONCLUSIÓN:")
print("• Los DATOS son 100% idénticos")
print("• Solo cambia la FECHA que aparece como índice")
print("• Es puramente cosmético/organizacional")
print("• En el 95% de casos, puedes ignorar esto completamente")

print("\n🤷‍♂️ ¿Cuándo importa?")
print("• Cuando haces gráficos y quieres que el eje X muestre fechas específicas")
print("• Cuando exportas reportes y necesitas coherencia con sistemas contables")
print("• Cuando trabajas con equipos que tienen convenciones específicas")
print("\n⚡ Para aprendizaje: puedes ignorar 'label' por completo")

🔍 CONFIRMACIÓN: Los resultados son exactamente iguales
============================================================
📊 DATOS DE ENERO:
Label='left':  4,600 ventas
Label='right': 4,600 ventas
¿Son iguales? True ✅

📅 DIFERENCIA: Solo las etiquetas de tiempo
Label='left':  etiqueta = 2023-12-31
Label='right': etiqueta = 2024-01-31

💡 CONCLUSIÓN:
• Los DATOS son 100% idénticos
• Solo cambia la FECHA que aparece como índice
• Es puramente cosmético/organizacional
• En el 95% de casos, puedes ignorar esto completamente

🤷‍♂️ ¿Cuándo importa?
• Cuando haces gráficos y quieres que el eje X muestre fechas específicas
• Cuando exportas reportes y necesitas coherencia con sistemas contables
• Cuando trabajas con equipos que tienen convenciones específicas

⚡ Para aprendizaje: puedes ignorar 'label' por completo

## 📋 Resumen y Puntos Clave

### Funciones Esenciales para Recordar

| **Función** | **Propósito** | **Ejemplo** |
|-------------|---------------|-------------|
| `datetime.strptime()` | String → Datetime | `datetime.strptime("25/11/2022", "%d/%m/%Y")` |
| `datetime.strftime()` | Datetime → String | `dt_object.strftime("%d/%m/%Y")` |
| `pd.to_datetime()` | Conversión inteligente a datetime | `pd.to_datetime(series)` |
| `pd.date_range()` | Crear rangos de fechas | `pd.date_range('2024-01-01', periods=10, freq='D')` |
| `series.dt.accessor` | Extraer componentes | `series.dt.year`, `series.dt.month` |
| `df.resample()` | Agregación temporal | `df.resample('M').mean()` |

### Códigos de Formato Más Utilizados

| **Código** | **Descripción** | **Ejemplo** |
|------------|-----------------|-------------|
| `%Y` | Año (4 dígitos) | 2024 |
| `%m` | Mes (01-12) | 03 |
| `%d` | Día (01-31) | 15 |
| `%H` | Hora 24h (00-23) | 14 |
| `%M` | Minuto (00-59) | 30 |
| `%S` | Segundo (00-59) | 45 |
| `%A` | Día de la semana | Friday |
| `%B` | Nombre del mes | March |

### 💡 Consejos Prácticos

1. **Siempre usar pd.to_datetime()** para conversiones en Pandas - es más robusto que datetime.strptime()
2. **El accesor .dt** es tu mejor amigo para extraer componentes de fechas en Series
3. **Usar resample()** para agregaciones temporales en lugar de groupby cuando sea posible
4. **Manejar zonas horarias** desde el inicio del proyecto para evitar problemas posteriores
5. **Crear índices temporales** facilita enormemente el filtrado y análisis de series temporales

### 🎯 Casos de Uso Comunes

- **Análisis de ventas**: Resampleo mensual/trimestral para identificar tendencias
- **Log analysis**: Filtrado por rangos de fechas para debugging
- **Reportes automáticos**: Extraer períodos específicos usando el accesor dt
- **Coordinación internacional**: Conversión entre zonas horarias para equipos globales
- **Series temporales**: Uso de índices datetime para análisis predictivo

---

### 📚 Referencias Adicionales

- [Documentación oficial de pandas datetime](https://pandas.pydata.org/docs/user_guide/timeseries.html)
- [Documentación de Python datetime](https://docs.python.org/3/library/datetime.html)
- [PyTZ timezone documentation](https://pythonhosted.org/pytz/)

**¡Recuerda!** Incluso los expertos consultan estas referencias regularmente. No intentes memorizar todo - enfócate en entender los conceptos y usa las guías de referencia. 🚀