# Manejo y Manipulación de Strings en Pandas

Este notebook documenta las principales técnicas para trabajar con strings (cadenas de texto) en Pandas, enfocado en Data Analytics:

- **Fundamentos básicos de strings en Python**
- **Accesor .str de Pandas para Series**
- **Transformación, búsqueda y extracción de texto**
- **Expresiones regulares aplicadas**
- **Limpieza y normalización de datos**
- **Casos prácticos en Data Analytics**

---

## 📖 Contenido

1. [Importar Librerías y Configuración Inicial](#1)
2. [Strings en Python - Fundamentos Básicos](#2)
3. [Introducción al Accesor .str en Pandas](#3)
    - 3.1 [Comportamiendo de None en pandas ](#3.1)
4. [Métodos de Transformación de Texto](#4)
5. [Búsqueda y Filtrado de Strings](#5)
6. [Extracción de Información con Patrones](#6)
7. [Expresiones Regulares en Pandas](#7)
8. [Limpieza y Normalización de Datos de Texto](#8)
9.  [División y Unión de Strings](#9)
10.  [Trabajar con Datos Categóricos de Texto](#10)
11.  [Análisis de Texto y Conteos](#11)
12.  [Casos Prácticos en Data Analytics](#12)

## 1. Importar Librerías y Configuración Inicial {#1}

Configuramos el entorno de trabajo e importamos las librerías necesarias para el manejo de strings en pandas:

In [1]:
# Importar librerías principales
import pandas as pd
import numpy as np
import re
import warnings
from typing import Union, List
import unicodedata
import string

# Configurar pandas para mejor visualización
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 50)
warnings.filterwarnings('ignore')

print("✅ Librerías importadas correctamente")
print(f"📦 Pandas version: {pd.__version__}")
print(f"📦 NumPy version: {np.__version__}")

✅ Librerías importadas correctamente
📦 Pandas version: 2.2.3
📦 NumPy version: 1.26.4

In [2]:

# Crear datos de ejemplo para demostración
datos_ejemplo = pd.DataFrame({
    
    'nombres'    : ['  JUAN PÉREZ  ',
                    'maría garcía'   , 
                    'Pedro Rodríguez', 
                    None, 
                    'ANA LÓPEZ'
                    ],
    'emails'     : ['juan.perez@email.com', 
                    'MARIA@GMAIL.COM', 
                    'pedro@empresa.co', 
                    '', 
                    'ana.lopez@yahoo.es'
                    ],
    'telefonos'  : ['+34 612-345-678'        , 
                    '34.123.456.789' , 
                    '612 345 678', 
                    '+1-555-0123', 
                    ''
                    ],
    'productos'  : ['PROD-001-A'             , 
                    'SERV-002-B'     , 
                    'PROD-003-C', 
                    'CONS-004-D', 
                    'PROD-005-E'],
    'direcciones': ['Calle Mayor 123, Madrid', 
                    'Av. Principal 456  Barcelona', 
                    'Plaza Central 789, Valencia', 
                    '', 
                    'Calle Luna 321, Sevilla']
})

print("\n📊 Datos de ejemplo creados:")
display(datos_ejemplo)

📊 Datos de ejemplo creados:

           nombres                emails        telefonos   productos                   direcciones
0     JUAN PÉREZ    juan.perez@email.com  +34 612-345-678  PROD-001-A       Calle Mayor 123, Madrid
1     maría garcía       MARIA@GMAIL.COM   34.123.456.789  SERV-002-B  Av. Principal 456  Barcelona
2  Pedro Rodríguez      pedro@empresa.co      612 345 678  PROD-003-C   Plaza Central 789, Valencia
3             None                            +1-555-0123  CONS-004-D
4        ANA LÓPEZ    ana.lopez@yahoo.es                   PROD-005-E       Calle Luna 321, Sevilla

## 2. Strings en Python - Fundamentos Básicos {#2}

Repaso rápido de los métodos esenciales de strings en Python antes de usar pandas:

In [3]:
# Métodos básicos de strings en Python
texto_ejemplo = "hola Mundo en Python  "
print(f"Texto original: '{texto_ejemplo}'")
print("=" * 50)

# Transformaciones básicas
print(f"upper():      '{texto_ejemplo.upper()}'")
print(f"lower():      '{texto_ejemplo.lower()}'")
print(f"strip():      '{texto_ejemplo.strip()}'")
print(f"title():      '{texto_ejemplo.title()}'")
print(f"capitalize(): '{texto_ejemplo.capitalize()}'")

Texto original: 'hola Mundo en Python  '
==================================================
upper():      'HOLA MUNDO EN PYTHON  '
lower():      'hola mundo en python  '
strip():      'hola Mundo en Python'
title():      'Hola Mundo En Python  '
capitalize(): 'Hola mundo en python  '

In [4]:
# Reemplazo y división
print("\n🔄 Reemplazo y división:")
texto = "Python es genial, Python es poderoso"
print(f"Original: '{texto}'")
print(f"replace(): '{texto.replace('Python', 'pandas')}'")

🔄 Reemplazo y división:
Original: 'Python es genial, Python es poderoso'
replace(): 'pandas es genial, pandas es poderoso'

In [5]:

# División
palabras = texto.split()
print(f"split(): {palabras}")

split(): ['Python', 'es', 'genial,', 'Python', 'es', 'poderoso']

In [6]:

# Unión
texto_unido = " - ".join(palabras)
print(f"join(): '{texto_unido}'")

join(): 'Python - es - genial, - Python - es - poderoso'

In [7]:
# Slicing y búsqueda
print("\n🔍 Slicing y búsqueda:")
frase = "Data Analytics con Python"
print(f"Original: '{frase}'")
print(f"Primeros 4 caracteres: '{frase[:4]}'")
print(f"Últimos 6 caracteres: '{frase[-6:]}'")
print(f"startswith('Data'): {frase.startswith('Data')}")
print(f"endswith('Python'): {frase.endswith('Python')}")
print(f"'Analytics' in frase: {'Analytics' in frase}")

🔍 Slicing y búsqueda:
Original: 'Data Analytics con Python'
Primeros 4 caracteres: 'Data'
Últimos 6 caracteres: 'Python'
startswith('Data'): True
endswith('Python'): True
'Analytics' in frase: True

In [8]:
# Limitaciones con listas/arrays
print("\n⚠️ LIMITACIÓN: Python puro vs Pandas")
lista_textos = ["texto1", "TEXTO2", "Texto3"]
print(f"Lista: {lista_textos}")
print("❌ lista_textos.upper() → Error!")
print("✅ En pandas: serie.str.upper() → ¡Funciona!")

⚠️ LIMITACIÓN: Python puro vs Pandas
Lista: ['texto1', 'TEXTO2', 'Texto3']
❌ lista_textos.upper() → Error!
✅ En pandas: serie.str.upper() → ¡Funciona!

## 3. Introducción al Accesor .str en Pandas {#3}

El accesor `.str` permite aplicar métodos de string a toda una Serie de pandas de manera vectorizada:

In [9]:
# Diferencia entre Python puro y Pandas .str
print("🆚 Python puro vs Pandas .str")
print("=" * 40)

# Crear una Serie de ejemplo
serie_nombres = pd.Series(['juan', 'MARÍA', 'Pedro', 'ANA'])
print(f"Serie original: {serie_nombres.tolist()}")

# Con pandas .str (vectorizado)
print(f"Con .str.upper(): {serie_nombres.str.upper().tolist()}")
print(f"Con .str.title(): {serie_nombres.str.title().tolist()}")
print(f"Con .str.len(): {serie_nombres.str.len().tolist()}")

🆚 Python puro vs Pandas .str
========================================
Serie original: ['juan', 'MARÍA', 'Pedro', 'ANA']
Con .str.upper(): ['JUAN', 'MARÍA', 'PEDRO', 'ANA']
Con .str.title(): ['Juan', 'María', 'Pedro', 'Ana']
Con .str.len(): [4, 5, 5, 3]

In [10]:
# Ventajas del accesor .str
print("\n✅ Ventajas del accesor .str:")
print("1. Operaciones vectorizadas (más rápidas)")
print("2. Manejo automático de valores NaN/None")
print("3. Métodos específicos para DataFrames")
print("4. Integración perfecta con indexing booleano")

# Demostrar manejo de NaN
serie_con_nan = pd.Series(['texto', None, 'OTRO', '', np.nan])
print(f"\nSerie con NaN: {serie_con_nan.tolist()}")
print(f"Con .str.upper(): {serie_con_nan.str.upper().tolist()}")
print("📝 Nota: Los NaN se mantienen como NaN automáticamente")

✅ Ventajas del accesor .str:
1. Operaciones vectorizadas (más rápidas)
2. Manejo automático de valores NaN/None
3. Métodos específicos para DataFrames
4. Integración perfecta con indexing booleano

Serie con NaN: ['texto', None, 'OTRO', '', nan]
Con .str.upper(): ['TEXTO', None, 'OTRO', '', nan]
📝 Nota: Los NaN se mantienen como NaN automáticamente

In [11]:
# Aplicar .str a nuestros datos de ejemplo
print("📊 Aplicando .str a datos reales:")
print("\nNombres originales vs limpios:")
print("Original:", datos_ejemplo['nombres'].tolist())
print("Limpios: ", datos_ejemplo['nombres'].str.strip().str.title().tolist())

print("\nEmails en minúsculas:")
print("Original:", datos_ejemplo['emails'].tolist())
print("Minúsc.: ", datos_ejemplo['emails'].str.lower().tolist())

📊 Aplicando .str a datos reales:

Nombres originales vs limpios:
Original: ['  JUAN PÉREZ  ', 'maría garcía', 'Pedro Rodríguez', None, 'ANA LÓPEZ']
Limpios:  ['Juan Pérez', 'María García', 'Pedro Rodríguez', None, 'Ana López']

Emails en minúsculas:
Original: ['juan.perez@email.com', 'MARIA@GMAIL.COM', 'pedro@empresa.co', '', 'ana.lopez@yahoo.es']
Minúsc.:  ['juan.perez@email.com', 'maria@gmail.com', 'pedro@empresa.co', '', 'ana.lopez@yahoo.es']

### 3.1 Comportamiento de None en pandas {3.1}

In [12]:
# Demostración: None vs NaN en pandas
print("🔍 Diferencia entre None y NaN en pandas:")
print("=" * 50)

# Crear ejemplos con None y NaN
datos_mixed = pd.Series(['texto1', None, 'texto3', np.nan, 'texto5'])
print("Serie con None y NaN:")
print(datos_mixed)
print(f"Tipos: {datos_mixed.apply(type).tolist()}")
print(f"Dtype de la serie: {datos_mixed.dtype}")
print()

🔍 Diferencia entre None y NaN en pandas:
==================================================
Serie con None y NaN:
0    texto1
1      None
2    texto3
3       NaN
4    texto5
dtype: object
Tipos: [<class 'str'>, <class 'NoneType'>, <class 'str'>, <class 'float'>, <class 'str'>]
Dtype de la serie: object

In [13]:

# Verificar qué detecta pandas como nulo
print("🔍 Detección de valores nulos:")
print(f"pd.isna(): {pd.isna(datos_mixed).tolist()}")
print(f"pd.isnull(): {pd.isnull(datos_mixed).tolist()}")
print(f"datos_mixed.isna(): {datos_mixed.isna().tolist()}")
print()

🔍 Detección de valores nulos:
pd.isna(): [False, True, False, True, False]
pd.isnull(): [False, True, False, True, False]
datos_mixed.isna(): [False, True, False, True, False]

In [14]:

# Comportamiento con operaciones .str
print("📝 Comportamiento con operaciones .str:")
print("Serie original:")
print(datos_mixed)
print("\nCon .str.upper():")
resultado = datos_mixed.str.upper()
print(resultado)
print(f"Tipos después de .str: {resultado.apply(type).tolist()}")
print()

📝 Comportamiento con operaciones .str:
Serie original:
0    texto1
1      None
2    texto3
3       NaN
4    texto5
dtype: object

Con .str.upper():
0    TEXTO1
1      None
2    TEXTO3
3       NaN
4    TEXTO5
dtype: object
Tipos después de .str: [<class 'str'>, <class 'NoneType'>, <class 'str'>, <class 'float'>, <class 'str'>]

In [15]:

print("💡 EXPLICACIÓN:")
print("─" * 30)
print("• None = objeto Python (tipo 'NoneType')")
print("• NaN = Not a Number (tipo 'float', valor np.nan)")
print("• Pandas convierte None → NaN automáticamente en:")
print("  - Series numéricas")
print("  - Operaciones que requieren homogeneidad")
print("• En Series 'object' (mixtas), None puede mantenerse como None")
print("• Ambos se consideran 'valores faltantes' por pandas")
print()

💡 EXPLICACIÓN:
──────────────────────────────
• None = objeto Python (tipo 'NoneType')
• NaN = Not a Number (tipo 'float', valor np.nan)
• Pandas convierte None → NaN automáticamente en:
  - Series numéricas
  - Operaciones que requieren homogeneidad
• En Series 'object' (mixtas), None puede mantenerse como None
• Ambos se consideran 'valores faltantes' por pandas

In [16]:

# Demostrar conversión automática
print("🔄 Conversión automática en diferentes contextos:")

# Serie solo de strings
serie_strings = pd.Series(['a', 'b', None, 'd'])
print(f"Serie strings: {serie_strings.tolist()}")
print(f"Tipos: {serie_strings.apply(lambda x: type(x).__name__).tolist()}")

# Forzar conversión a string
serie_strings_str = pd.Series(['a', 'b', None, 'd'], dtype='string')
print(f"Con dtype='string': {serie_strings_str.tolist()}")
print(f"Tipos: {serie_strings_str.apply(lambda x: type(x).__name__).tolist()}")

# Serie numérica con None
serie_numerica = pd.Series([1, 2, None, 4])
print(f"Serie numérica: {serie_numerica.tolist()}")
print(f"Tipos: {serie_numerica.apply(lambda x: type(x).__name__).tolist()}")
print(f"Dtype: {serie_numerica.dtype}")

🔄 Conversión automática en diferentes contextos:
Serie strings: ['a', 'b', None, 'd']
Tipos: ['str', 'str', 'NoneType', 'str']
Con dtype='string': ['a', 'b', <NA>, 'd']
Tipos: ['str', 'str', 'NAType', 'str']
Serie numérica: [1.0, 2.0, nan, 4.0]
Tipos: ['float', 'float', 'float', 'float']
Dtype: float64

#### 🎯 Razones por las que None puede quedarse como None:


##### 1. Tipo de Serie (dtype)

In [17]:
# Object dtype puede mantener None
serie_object = pd.Series(['texto', None, 'otro'], dtype='object')  # None se mantiene
display(serie_object)
# String dtype convierte a pd.NA
serie_string = pd.Series(['texto', None, 'otro'], dtype='string')  # None → pd.NA
display(serie_string)

0    texto
1     None
2     otro
dtype: object

0    texto
1     <NA>
2     otro
dtype: string

In [18]:
# Series con tipos mixtos mantienen None
serie_mixta = pd.Series(['texto', 123, None, True])  # None se mantiene# 
display(serie_mixta)

0    texto
1      123
2     None
3     True
dtype: object

In [19]:
# Al crear directamente
df = pd.DataFrame({'col': ['a', None, 'c']})  # None se mantiene inicialmente
display(df)    
# Al asignar después
df.loc[0, 'col'] = None  # Puede convertirse según el contexto
display(df)

    col
0     a
1  None
2     c

    col
0  None
1  None
2     c

##### Como Forzar la conversión

In [20]:
# Métodos para unificar valores nulos
print("🛠️ Métodos para unificar valores nulos:")

# Datos con None y NaN mezclados
datos_mezclados = pd.Series(['texto1', None, 'texto3', np.nan, ''])

print("Original:")
display(datos_mezclados)

# Método 1: Reemplazar None por NaN
metodo1 = datos_mezclados.replace({None: np.nan})
print(f"\nMétodo 1 - replace None: {metodo1.tolist()}")

# Método 2: Usar where con condición
metodo2 = datos_mezclados.where(pd.notnull(datos_mezclados), np.nan)
print(f"Método 2 - where: {metodo2.tolist()}")

# Método 3: Conversión explícita
metodo3 = datos_mezclados.astype('object').where(datos_mezclados.notna(), np.nan)
print(f"Método 3 - astype + where: {metodo3.tolist()}")

🛠️ Métodos para unificar valores nulos:
Original:

0    texto1
1      None
2    texto3
3       NaN
4
dtype: object

Método 1 - replace None: ['texto1', nan, 'texto3', nan, '']
Método 2 - where: ['texto1', nan, 'texto3', nan, '']
Método 3 - astype + where: ['texto1', nan, 'texto3', nan, '']

In [21]:
# Función de limpieza robusta
def normalizar_nulos(serie):
    """Normaliza todos los valores nulos a NaN"""
    return serie.replace({None: np.nan, '': np.nan, 'null': np.nan, 'NULL': np.nan})

# Aplicar a nuestros datos de ejemplo
print("🧹 Normalización práctica:")
display(datos_ejemplo)
datos_ejemplo_norm = datos_ejemplo.copy()
for col in datos_ejemplo_norm.select_dtypes(include=['object']):
    datos_ejemplo_norm[col] = normalizar_nulos(datos_ejemplo_norm[col])

print("Datos después de normalización:")
display(datos_ejemplo_norm)

print("Valores nulos por columna después de normalización:")

display(datos_ejemplo_norm.isnull().sum())

🧹 Normalización práctica:

           nombres                emails        telefonos   productos                   direcciones
0     JUAN PÉREZ    juan.perez@email.com  +34 612-345-678  PROD-001-A       Calle Mayor 123, Madrid
1     maría garcía       MARIA@GMAIL.COM   34.123.456.789  SERV-002-B  Av. Principal 456  Barcelona
2  Pedro Rodríguez      pedro@empresa.co      612 345 678  PROD-003-C   Plaza Central 789, Valencia
3             None                            +1-555-0123  CONS-004-D
4        ANA LÓPEZ    ana.lopez@yahoo.es                   PROD-005-E       Calle Luna 321, Sevilla

Datos después de normalización:

           nombres                emails        telefonos   productos                   direcciones
0     JUAN PÉREZ    juan.perez@email.com  +34 612-345-678  PROD-001-A       Calle Mayor 123, Madrid
1     maría garcía       MARIA@GMAIL.COM   34.123.456.789  SERV-002-B  Av. Principal 456  Barcelona
2  Pedro Rodríguez      pedro@empresa.co      612 345 678  PROD-003-C   Plaza Central 789, Valencia
3              NaN                   NaN      +1-555-0123  CONS-004-D                           NaN
4        ANA LÓPEZ    ana.lopez@yahoo.es              NaN  PROD-005-E       Calle Luna 321, Sevilla

Valores nulos por columna después de normalización:

nombres        1
emails         1
telefonos      1
productos      0
direcciones    1
dtype: int64

📝 Resumen práctico:

- None = valor Python que puede mantenerse en Series object
- NaN = valor pandas/numpy para "faltante"
- Ambos son detectados por .isna() y .isnull()
- Para análisis: mejor convertir todo a NaN para consistencia
- Las operaciones .str manejan ambos correctamente

## 4. Métodos de Transformación de Texto {#4}

Los métodos de transformación permiten cambiar el formato y caso de los strings de manera consistente:

In [22]:
# Métodos de transformación de caso
print("🔤 Transformaciones de caso:")
texto_muestra = pd.Series(['hola mundo', 'DATA analytics', 'PyThOn PaNdAs', '  TEXTO  '])

display(texto_muestra)

transformaciones = {
    'Original'    : texto_muestra,
    'upper()'     : texto_muestra.str.upper(),
    'lower()'     : texto_muestra.str.lower(),
    'title()'     : texto_muestra.str.title(),
    'capitalize()': texto_muestra.str.capitalize(),
    'swapcase()'  : texto_muestra.str.swapcase()
}

df_transformaciones = pd.DataFrame(transformaciones)
display(df_transformaciones)

🔤 Transformaciones de caso:

0        hola mundo
1    DATA analytics
2     PyThOn PaNdAs
3           TEXTO
dtype: object

         Original         upper()         lower()         title()    capitalize()      swapcase()
0      hola mundo      HOLA MUNDO      hola mundo      Hola Mundo      Hola mundo      HOLA MUNDO
1  DATA analytics  DATA ANALYTICS  data analytics  Data Analytics  Data analytics  data ANALYTICS
2   PyThOn PaNdAs   PYTHON PANDAS   python pandas   Python Pandas   Python pandas   pYtHoN pAnDaS
3         TEXTO           TEXTO           texto           Texto           texto           texto

In [23]:
# Métodos de limpieza de espacios
print("\n🧹 Limpieza de espacios:")
textos_espacios = pd.Series(['  inicio  ', '\ttabs\t', '\nespacios\n ', '  normal  '])

display(textos_espacios)

limpieza_espacios = pd.DataFrame({
    'Original': textos_espacios,
    'strip()' : textos_espacios.str.strip(),
    'lstrip()': textos_espacios.str.lstrip(),
    'rstrip()': textos_espacios.str.rstrip()
})
display(limpieza_espacios)

🧹 Limpieza de espacios:

0         inicio
1         \ttabs\t
2    \nespacios\n
3         normal
dtype: object

        Original   strip()     lstrip()    rstrip()
0       inicio      inicio     inicio        inicio
1       \ttabs\t      tabs       tabs\t      \ttabs
2  \nespacios\n   espacios  espacios\n   \nespacios
3       normal      normal     normal        normal

In [24]:
# Aplicación práctica: limpieza de nombres
print("\n🏷️ Caso práctico: Normalización de nombres")
nombres_sucios = pd.Series([
    '  juan pérez  ',
    'MARÍA GARCÍA',
    'pedro   rodríguez',
    '\tana\tlópez\t',
    'luis  HERNÁNDEZ '
])



print("Nombres originales:")
for i, nombre in enumerate(nombres_sucios):
    print(f"{i+1}. '{nombre}'")

# Pipeline de limpieza
nombres_limpios = (nombres_sucios
                   .str.strip()           # Quitar espacios
                   .str.replace('\t', ' ') # Quitar tabs y renplazarlos por un espacio
                   .str.replace(r'\s+', ' ', regex=True)  # Normalizar espacios múltiples
                   .str.title())          # Formato título

print("\nNombres después de limpieza:")
for i, nombre in enumerate(nombres_limpios):
    print(f"{i+1}. '{nombre}'")

# Crear DataFrame comparativo
df_nombres = pd.DataFrame({
    'Original': nombres_sucios,
    'Limpio': nombres_limpios
})
print("\n📊 Comparación:")
display(df_nombres)

🏷️ Caso práctico: Normalización de nombres
Nombres originales:
1. '  juan pérez  '
2. 'MARÍA GARCÍA'
3. 'pedro   rodríguez'
4. '	ana	lópez	'
5. 'luis  HERNÁNDEZ '

Nombres después de limpieza:
1. 'Juan Pérez'
2. 'María García'
3. 'Pedro Rodríguez'
4. 'Ana López'
5. 'Luis Hernández'

📊 Comparación:

            Original           Limpio
0       juan pérez         Juan Pérez
1       MARÍA GARCÍA     María García
2  pedro   rodríguez  Pedro Rodríguez
3     \tana\tlópez\t        Ana López
4   luis  HERNÁNDEZ    Luis Hernández

## 5. Búsqueda y Filtrado de Strings {#5}

Los métodos de búsqueda permiten filtrar y encontrar patrones específicos en los datos de texto:

In [25]:
# Métodos básicos de búsqueda
print("🔍 Métodos de búsqueda básicos:")
textos_busqueda = pd.Series([
    'python analytics',
    'data science',
    'machine learning',
    'Python programming',
    'Data Analytics',
    None,
    ''
])

print("Textos de ejemplo:")
display(textos_busqueda)
print()

# Búsquedas básicas
print("📝 Resultados de búsqueda:")
print(f"Contiene 'data': {textos_busqueda.str.contains('data', case=False, na=False).tolist()}")
print(f"Empieza con 'python': {textos_busqueda.str.startswith('python', na=False).tolist()}")
print(f"Termina con 'ing': {textos_busqueda.str.endswith('ing', na=False).tolist()}")

🔍 Métodos de búsqueda básicos:
Textos de ejemplo:

0      python analytics
1          data science
2      machine learning
3    Python programming
4        Data Analytics
5                  None
6
dtype: object

📝 Resultados de búsqueda:
Contiene 'data': [False, True, False, False, True, False, False]
Empieza con 'python': [True, False, False, False, False, False, False]
Termina con 'ing': [False, False, True, True, False, False, False]

In [27]:
# Filtrado práctico con nuestros datos
print("🎯 Filtrado práctico con datos reales:")
print("\nEmails que contienen 'gmail':")
gmail_mask = datos_ejemplo['emails'].str.contains('gmail', case=False, na=False)
emails_gmail = datos_ejemplo[gmail_mask]['emails']
print(emails_gmail.tolist())

print("\nProductos que empiezan con 'PROD':")
prod_mask = datos_ejemplo['productos'].str.startswith('PROD', na=False)
productos_prod = datos_ejemplo[prod_mask]['productos']
print(productos_prod.tolist())

print("\nDirecciones que terminan con ciudades específicas:")
ciudades = ['Madrid', 'Barcelona', 'Valencia']
for ciudad in ciudades:
    ciudad_mask = datos_ejemplo['direcciones'].str.endswith(ciudad, na=False)
    if ciudad_mask.any():
        print(f"  {ciudad:10}: {datos_ejemplo[ciudad_mask]['direcciones'].iloc[0]}")

🎯 Filtrado práctico con datos reales:

Emails que contienen 'gmail':
['MARIA@GMAIL.COM']

Productos que empiezan con 'PROD':
['PROD-001-A', 'PROD-003-C', 'PROD-005-E']

Direcciones que terminan con ciudades específicas:
  Madrid    : Calle Mayor 123, Madrid
  Barcelona : Av. Principal 456  Barcelona
  Valencia  : Plaza Central 789, Valencia

In [ ]:
# Búsquedas avanzadas con múltiples condiciones
print("\n🔄 Búsquedas avanzadas:")

# Crear datos más complejos para demostrar
productos_complejos = pd.Series([
    'LAPTOP-HP-001',
    'MOUSE-LOGITECH-002', 
    'MONITOR-SAMSUNG-003',
    'LAPTOP-DELL-004',
    'KEYBOARD-HP-005',
    'TABLET-APPLE-006'
])

print("Productos disponibles:")
print(productos_complejos.tolist())

# Filtros múltiples
print("\n📊 Aplicando filtros:")

# Productos que contienen 'HP' o 'DELL'
marcas_filtro = productos_complejos.str.contains('HP|DELL', regex=True)
print(f"Productos HP o DELL:")
print("\t\t", end="") 
print(*productos_complejos[marcas_filtro].tolist(), sep ="\n\t\t")
 
# Productos que NO son laptops
no_laptop = ~productos_complejos.str.contains('LAPTOP')
print(f"No laptops: ")
print("\t\t", end="") 
print(*no_laptop[marcas_filtro].tolist(), sep ="\n\t\t")


# Combinando condiciones
laptops_especificas = (productos_complejos.str.contains('LAPTOP') & 
                      productos_complejos.str.contains('HP|DELL'))
print(f"Laptops HP o DELL:")
print("\t\t", end="") 
print(*laptops_especificas[marcas_filtro].tolist(), sep ="\n\t\t")

🔄 Búsquedas avanzadas:
Productos disponibles:
['LAPTOP-HP-001', 'MOUSE-LOGITECH-002', 'MONITOR-SAMSUNG-003', 'LAPTOP-DELL-004', 'KEYBOARD-HP-005', 'TABLET-APPLE-006']

📊 Aplicando filtros:
Productos HP o DELL:
		LAPTOP-HP-001
		LAPTOP-DELL-004
		KEYBOARD-HP-005
No laptops:
		False
		False
		True
Laptops HP o DELL:
		True
		True
		False

## 6. Extracción de Información con Patrones {#6}

Los métodos de extracción permiten obtener información específica de strings usando patrones y grupos:

In [55]:
# Extracción básica con .str.extract()
print("📤 Extracción de información:")

# Datos con patrones claros
codigos_productos = pd.Series([
    'PROD-123-A',
    'SERV-456-B', 
    'CONS-789-C',
    'PROD-012-D',
    'SERV-345-E'
])

print("Códigos originales:")
print(codigos_productos.tolist())

# Extraer componentes usando grupos (paréntesis)
patron = r'([A-Z]+)-(\d+)-([A-Z])'
componentes = codigos_productos.str.extract(patron)
componentes.columns = ['Tipo', 'Numero', 'Categoria']

print("\n🔍 Componentes extraídos:")
display(componentes)

📤 Extracción de información:
Códigos originales:
['PROD-123-A', 'SERV-456-B', 'CONS-789-C', 'PROD-012-D', 'SERV-345-E']

🔍 Componentes extraídos:

   Tipo Numero Categoria
0  PROD    123         A
1  SERV    456         B
2  CONS    789         C
3  PROD    012         D
4  SERV    345         E

In [56]:
# Extracción de emails
print("\n📧 Extracción de información de emails:")
emails_ejemplo = pd.Series([
    'juan.perez@empresa.com',
    'maria@gmail.com',
    'pedro.rodriguez@universidad.edu',
    'ana.lopez@startup.io',
    'luis@consultora.es'
])

# Extraer usuario y dominio
patron_email = r'([^@]+)@(.+)'
partes_email = emails_ejemplo.str.extract(patron_email)
partes_email.columns = ['Usuario', 'Dominio']

print("Emails originales y componentes:")
resultado_emails = pd.DataFrame({
    'Email_Original': emails_ejemplo,
    'Usuario': partes_email['Usuario'],
    'Dominio': partes_email['Dominio']
})
display(resultado_emails)

📧 Extracción de información de emails:
Emails originales y componentes:

                    Email_Original          Usuario          Dominio
0           juan.perez@empresa.com       juan.perez      empresa.com
1                  maria@gmail.com            maria        gmail.com
2  pedro.rodriguez@universidad.edu  pedro.rodriguez  universidad.edu
3             ana.lopez@startup.io        ana.lopez       startup.io
4               luis@consultora.es             luis    consultora.es

In [58]:
# Extracción múltiple con .str.extractall()
print("\n🔢 Extracción múltiple de números:")
textos_numeros = pd.Series([
    'Precio: 150 euros, descuento: 20 euros',
    'Cantidad: 5 unidades, precio: 25 euros',
    'Total: 100, IVA: 21, final: 121'
])

# Extraer todos los números
patron_numeros = r'(\d+)'
todos_numeros = textos_numeros.str.extractall(patron_numeros)
print("Números extraídos:")
display(todos_numeros)

# .str.findall() para obtener listas
print("\n📋 Usando findall() para listas:")
listas_numeros = textos_numeros.str.findall(r'\d+')
print("Números como listas:")
for i, lista in enumerate(listas_numeros):
    print(f"Texto {i}: {lista}")

🔢 Extracción múltiple de números:
Números extraídos:

           0
  match
0 0      150
  1       20
1 0        5
  1       25
2 0      100
  1       21
  2      121

📋 Usando findall() para listas:
Números como listas:
Texto 0: ['150', '20']
Texto 1: ['5', '25']
Texto 2: ['100', '21', '121']

In [64]:
# Caso práctico: extraer información de URLs
print("\n🌐 Caso práctico: Análisis de URLs:")
urls_ejemplo = pd.Series([
    'https://www.google.com/search?q=pandas',
    'http://github.com/pandas-dev/pandas',
    'https://docs.python.org/3/library/re.html',
    'https://stackoverflow.com/questions/12345',
    'http://localhost:8080/admin/users',
    'ftp://example.com/resource'
])

# Extraer protocolo, dominio y path
patron_url = r'(https?|ftp?)://([^/]+)(.*)'
componentes_url = urls_ejemplo.str.extract(patron_url)
componentes_url.columns = ['Protocolo', 'Dominio', 'Path']

df_urls = pd.DataFrame({
    'URL_Original': urls_ejemplo,
    'Protocolo': componentes_url['Protocolo'],
    'Dominio': componentes_url['Dominio'],
    'Path': componentes_url['Path']
})

print("Análisis de URLs:")
display(df_urls)

🌐 Caso práctico: Análisis de URLs:
Análisis de URLs:

                                URL_Original Protocolo            Dominio                Path
0     https://www.google.com/search?q=pandas     https     www.google.com    /search?q=pandas
1        http://github.com/pandas-dev/pandas      http         github.com  /pandas-dev/pandas
2  https://docs.python.org/3/library/re.html     https    docs.python.org  /3/library/re.html
3  https://stackoverflow.com/questions/12345     https  stackoverflow.com    /questions/12345
4          http://localhost:8080/admin/users      http     localhost:8080        /admin/users
5                 ftp://example.com/resource       ftp        example.com           /resource

In [65]:

# Análisis adicional
print("\n📊 Estadísticas de URLs:")
print(f"URLs con HTTPS: {componentes_url['Protocolo'].str.contains('https').sum()}")
print(f"Dominios únicos: {componentes_url['Dominio'].nunique()}")
print(f"URLs con paths largos (>20 chars): {(componentes_url['Path'].str.len() > 20).sum()}")

📊 Estadísticas de URLs:
URLs con HTTPS: 3
Dominios únicos: 6
URLs con paths largos (>20 chars): 0

## 7. Expresiones Regulares en Pandas {#7}

Las expresiones regulares (regex) permiten búsquedas y reemplazos complejos de patrones en texto:

In [66]:
# Introducción a regex en pandas
print("🎯 Expresiones regulares en pandas:")

# Datos con patrones complejos
textos_regex = pd.Series([
    'Teléfono: +34 612-345-678',
    'Móvil: 34.123.456.789',
    'Fijo: 91 234 56 78',
    'Internacional: +1-555-0123',
    'Sin formato: 612345678'
])

print("Textos originales:")
print(textos_regex.tolist())

# Buscar números de teléfono con regex
patron_telefono = r'\+?[\d\s\.-]{9,15}'
tiene_telefono = textos_regex.str.contains(patron_telefono, regex=True)
print(f"\nContienen teléfonos: {tiene_telefono.tolist()}")

# Extraer solo los números
numeros_extraidos = textos_regex.str.extract(r'([\d\s\.-]+)')
print("\nNúmeros extraídos:")
print(numeros_extraidos[0].tolist())

🎯 Expresiones regulares en pandas:
Textos originales:
['Teléfono: +34 612-345-678', 'Móvil: 34.123.456.789', 'Fijo: 91 234 56 78', 'Internacional: +1-555-0123', 'Sin formato: 612345678']

Contienen teléfonos: [True, True, True, True, True]

Números extraídos:
[' ', ' 34.123.456.789', ' 91 234 56 78', ' ', ' ']

In [67]:
# Validación de emails con regex
print("\n📧 Validación de emails:")
emails_validar = pd.Series([
    'usuario@dominio.com',
    'test.email@empresa.co.uk',
    'invalid-email',
    'otro@ejemplo.org',
    'mal.formato@',
    '@sin-usuario.com',
    'correcto@test-domain.net'
])

# Patrón básico de email
patron_email_simple = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
emails_validos = emails_validar.str.match(patron_email_simple)

df_validacion = pd.DataFrame({
    'Email': emails_validar,
    'Es_Valido': emails_validos
})
print(df_validacion)

📧 Validación de emails:
                      Email  Es_Valido
0       usuario@dominio.com       True
1  test.email@empresa.co.uk       True
2             invalid-email      False
3          otro@ejemplo.org       True
4              mal.formato@      False
5          @sin-usuario.com      False
6  correcto@test-domain.net       True

In [68]:
# Reemplazos avanzados con regex
print("\n🔄 Reemplazos con regex:")

# Texto con diferentes formatos de fecha
fechas_mixtas = pd.Series([
    'Fecha: 15/03/2024',
    'Date: 2024-03-15',
    'Día: 15-Mar-2024',
    'Today: March 15, 2024',
    'Hoy: 15.03.24'
])

print("Fechas originales:")
print(fechas_mixtas.tolist())

# Normalizar formato DD/MM/YYYY
# Patrón para DD/MM/YYYY o DD-MM-YYYY
patron_fecha1 = r'(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})'
fechas_normalizadas = fechas_mixtas.str.replace(patron_fecha1, r'\1/\2/\3', regex=True)

print("\nDespués de normalizar separadores:")
print(fechas_normalizadas.tolist())

# Limpiar prefijos
fechas_limpias = fechas_normalizadas.str.replace(r'^[^:]+:\s*', '', regex=True)
print("\nDespués de limpiar prefijos:")
print(fechas_limpias.tolist())

🔄 Reemplazos con regex:
Fechas originales:
['Fecha: 15/03/2024', 'Date: 2024-03-15', 'Día: 15-Mar-2024', 'Today: March 15, 2024', 'Hoy: 15.03.24']

Después de normalizar separadores:
['Fecha: 15/03/2024', 'Date: 2024/03/15', 'Día: 15-Mar-2024', 'Today: March 15, 2024', 'Hoy: 15.03.24']

Después de limpiar prefijos:
['15/03/2024', '2024/03/15', '15-Mar-2024', 'March 15, 2024', '15.03.24']

In [ ]:
# Casos prácticos con regex
print("\n💼 Casos prácticos:")

# 1. Limpiar códigos de producto
codigos_sucios = pd.Series([
    'PROD_001_VERSION_A',
    'SERV-002-TYPE-B',
    'CONS.003.CAT.C',
    'ITEM/004/SPEC/D'
])

print("1. Limpieza de códigos:")
print("Originales:", codigos_sucios.tolist())

# Normalizar separadores a guiones
codigos_limpios = codigos_sucios.str.replace(r'[_./]', '-', regex=True)
print("Normalizados:", codigos_limpios.tolist())

💼 Casos prácticos:
1. Limpieza de códigos:
Originales: ['PROD_001_VERSION_A', 'SERV-002-TYPE-B', 'CONS.003.CAT.C', 'ITEM/004/SPEC/D']
Normalizados: ['PROD-001-VERSION-A', 'SERV-002-TYPE-B', 'CONS-003-CAT-C', 'ITEM-004-SPEC-D']

In [72]:
# 2. Extraer información de direcciones
direcciones_complejas = pd.Series([
    'Calle Mayor 123, 4º B, 28001 Madrid',
    'Av. Diagonal 456, Ático, 08001 Barcelona', 
    'Plaza España 789, 1º A, 46001 Valencia'
])

print("\n2. Análisis de direcciones:")
# Extraer código postal y ciudad
patron_direccion = r'(\d{5})\s+([A-Za-záéíóúñ]+)$'
info_direccion = direcciones_complejas.str.extract(patron_direccion)
info_direccion.columns = ['Codigo_Postal', 'Ciudad']

df_direcciones = pd.DataFrame({
    'Direccion_Completa': direcciones_complejas,
    'Codigo_Postal': info_direccion['Codigo_Postal'],
    'Ciudad': info_direccion['Ciudad']
})
display(df_direcciones)

2. Análisis de direcciones:

                         Direccion_Completa Codigo_Postal     Ciudad
0       Calle Mayor 123, 4º B, 28001 Madrid         28001     Madrid
1  Av. Diagonal 456, Ático, 08001 Barcelona         08001  Barcelona
2    Plaza España 789, 1º A, 46001 Valencia         46001   Valencia

## 8. Limpieza y Normalización de Datos de Texto {#8}

La limpieza de datos de texto es fundamental en Data Analytics para asegurar consistencia y calidad:

In [73]:
# Pipeline completo de limpieza de texto
print("🧹 Pipeline de limpieza de texto:")

# Datos sucios realistas
datos_sucios = pd.Series([
    '  JOSÉ MARÍA GARCÍA  ',
    'María-José Rodríguez\t',
    'Pedro   Pérez   López',
    '\n Ana   Sofía  Martín\n',
    'LUIS HERNÁNDEZ GONZÁLEZ',
    '   Dr. Carmen Ruiz  ',
    'Dña. Isabel Moreno   '
])

print("Datos originales:")
for i, dato in enumerate(datos_sucios):
    print(f"{i+1}. '{dato}'")

def limpiar_texto(serie):
    """Pipeline completo de limpieza de texto"""
    return (serie
            .str.strip()                          # Quitar espacios inicio/fin
            .str.replace('\t', ' ', regex=False)  # Reemplazar tabs
            .str.replace('\n', ' ', regex=False)  # Reemplazar saltos de línea
            .str.replace(r'\s+', ' ', regex=True) # Normalizar espacios múltiples
            .str.replace(r'^(Dr\.|Dra\.|D\.|Dña\.)\s*', '', regex=True)  # Quitar títulos
            .str.title()                          # Formato título
            .str.strip())                         # Limpieza final

datos_limpios = limpiar_texto(datos_sucios)

print("\nDatos después de limpieza:")
for i, dato in enumerate(datos_limpios):
    print(f"{i+1}. '{dato}'")

# Comparación lado a lado
df_comparacion = pd.DataFrame({
    'Original': datos_sucios,
    'Limpio': datos_limpios
})
print("\n📊 Comparación:")
display(df_comparacion)

🧹 Pipeline de limpieza de texto:
Datos originales:
1. '  JOSÉ MARÍA GARCÍA  '
2. 'María-José Rodríguez	'
3. 'Pedro   Pérez   López'
4. '
 Ana   Sofía  Martín
'
5. 'LUIS HERNÁNDEZ GONZÁLEZ'
6. '   Dr. Carmen Ruiz  '
7. 'Dña. Isabel Moreno   '

Datos después de limpieza:
1. 'José María García'
2. 'María-José Rodríguez'
3. 'Pedro Pérez López'
4. 'Ana Sofía Martín'
5. 'Luis Hernández González'
6. 'Carmen Ruiz'
7. 'Isabel Moreno'

📊 Comparación:

                   Original                   Limpio
0       JOSÉ MARÍA GARCÍA          José María García
1    María-José Rodríguez\t     María-José Rodríguez
2     Pedro   Pérez   López        Pedro Pérez López
3  \n Ana   Sofía  Martín\n         Ana Sofía Martín
4   LUIS HERNÁNDEZ GONZÁLEZ  Luis Hernández González
5         Dr. Carmen Ruiz                Carmen Ruiz
6     Dña. Isabel Moreno               Isabel Moreno

In [74]:
# Normalización de caracteres especiales
print("\n🌍 Normalización de caracteres especiales:")

# Función para quitar acentos
def quitar_acentos(texto):
    """Quita acentos y caracteres especiales"""
    if pd.isna(texto):
        return texto
    # Normalizar a NFD (Canonical Decomposition)
    texto_normalizado = unicodedata.normalize('NFD', texto)
    # Filtrar solo caracteres ASCII
    texto_sin_acentos = ''.join(c for c in texto_normalizado if unicodedata.category(c) != 'Mn')
    return texto_sin_acentos

# Aplicar a datos con acentos
textos_acentos = pd.Series([
    'José María Pérez',
    'Niña con piñata',
    'Müller & Söhne',
    'Français café',
    'São Paulo - Brasil'
])

print("Textos con acentos:")
print(textos_acentos.tolist())

# Quitar acentos
textos_sin_acentos = textos_acentos.apply(quitar_acentos)
print("\nTextos sin acentos:")
print(textos_sin_acentos.tolist())

# También podemos hacerlo directamente con str.normalize()
print("\nUsando .str.encode() y .str.decode():")
# Método alternativo (menos control)
textos_ascii = (textos_acentos
                .str.encode('ascii', 'ignore')
                .str.decode('ascii'))
display(textos_ascii.tolist())

🌍 Normalización de caracteres especiales:
Textos con acentos:
['José María Pérez', 'Niña con piñata', 'Müller & Söhne', 'Français café', 'São Paulo - Brasil']

Textos sin acentos:
['Jose Maria Perez', 'Nina con pinata', 'Muller & Sohne', 'Francais cafe', 'Sao Paulo - Brasil']

Usando .str.encode() y .str.decode():

['Jos Mara Prez',
 'Nia con piata',
 'Mller & Shne',
 'Franais caf',
 'So Paulo - Brasil']

In [80]:
# 2. Estandarización de empresas/organizaciones
print("\n🏢 Estandarización de nombres de empresas:")

empresas_diversas = pd.Series([
    'MICROSOFT CORP.',
    'Apple Inc',
    'Google LLC',
    'Amazon.com, Inc.',
    'Facebook, Inc.',
    'Tesla Motors',
    'IBM Corporation'
])

def normalizar_empresa(empresa):
    """Normaliza nombres de empresas"""
    if pd.isna(empresa):
        return empresa
    
    # Diccionario de sufijos a normalizar
    sufijos = {
        r'\bCORP\.?$': 'Corporation',
        r'\bINC\.?$': 'Inc.',
        r'\bLLC\.?$': 'LLC',
        r'\bLTD\.?$': 'Ltd.',
        r',?\s*INC\.?$': ', Inc.'
    }
    
    empresa_norm = empresa.strip()
    # Aplicar normalizaciones
    for patron, reemplazo in sufijos.items():
        empresa_norm = re.sub(patron, reemplazo, empresa_norm, flags=re.IGNORECASE)
    
    return empresa_norm.title()

empresas_normalizadas = empresas_diversas.apply(normalizar_empresa)

print("Normalización de empresas:")
df_empresas = pd.DataFrame({
    'Original': empresas_diversas,
    'Normalizado': empresas_normalizadas
})
display(df_empresas)

🏢 Estandarización de nombres de empresas:
Normalización de empresas:

           Original            Normalizado
0   MICROSOFT CORP.  Microsoft Corporation
1         Apple Inc            Apple, Inc.
2        Google LLC             Google Llc
3  Amazon.com, Inc.       Amazon.Com, Inc.
4    Facebook, Inc.         Facebook, Inc.
5      Tesla Motors           Tesla Motors
6   IBM Corporation        Ibm Corporation

In [81]:

# 3. Función de limpieza integral
print("\n🎯 Función de limpieza integral:")

def limpieza_integral(serie_texto):
    """Función completa de limpieza para Data Analytics"""
    return (serie_texto
            .astype(str)                          # Asegurar que sea string
            .str.strip()                          # Espacios inicio/fin
            .str.replace(r'\s+', ' ', regex=True) # Espacios múltiples
            .str.replace(r'[^\w\s.-]', '', regex=True)  # Solo alfanuméricos y algunos especiales
            .str.title()                          # Formato título
            .replace('Nan', np.nan))              # Convertir 'Nan' a NaN real

# Ejemplo con datos muy sucios
datos_muy_sucios = pd.Series([
    '  texto@#$% sucio  ',
    'MAYÚSCULAS!!!',
    '   múltiples    espacios   ',
    '',
    None,
    'normal'
])

print("Datos muy sucios:")
print(datos_muy_sucios.tolist())
print("Después de limpieza integral:")
print(limpieza_integral(datos_muy_sucios).tolist())

🎯 Función de limpieza integral:
Datos muy sucios:
['  texto@#$% sucio  ', 'MAYÚSCULAS!!!', '   múltiples    espacios   ', '', None, 'normal']
Después de limpieza integral:
['Texto Sucio', 'Mayúsculas', 'Múltiples Espacios', '', 'None', 'Normal']

## 9. División y Unión de Strings {#9}

Las operaciones de división y unión son esenciales para reestructurar y combinar datos de texto:

In [82]:
# División básica con .str.split()
print("✂️ División de strings:")

# Datos con información estructurada
nombres_completos = pd.Series([
    'Juan Pérez García',
    'María José Rodríguez López',
    'Pedro Martín',
    'Ana Sofía Hernández Ruiz',
    'Luis González'
])

print("Nombres completos:")
print(nombres_completos.tolist())

✂️ División de strings:
Nombres completos:
['Juan Pérez García', 'María José Rodríguez López', 'Pedro Martín', 'Ana Sofía Hernández Ruiz', 'Luis González']

In [83]:

# División simple (devuelve listas)
nombres_divididos = nombres_completos.str.split()
print(f"\nDivididos en listas: {nombres_divididos.tolist()}")

# División expandida (crea columnas)
nombres_expandidos = nombres_completos.str.split(expand=True)
nombres_expandidos.columns = ['Nombre1', 'Nombre2', 'Nombre3', 'Nombre4']
print("\nDivididos en columnas:")
display(nombres_expandidos)

Divididos en listas: [['Juan', 'Pérez', 'García'], ['María', 'José', 'Rodríguez', 'López'], ['Pedro', 'Martín'], ['Ana', 'Sofía', 'Hernández', 'Ruiz'], ['Luis', 'González']]

Divididos en columnas:

  Nombre1   Nombre2    Nombre3 Nombre4
0    Juan     Pérez     García    None
1   María      José  Rodríguez   López
2   Pedro    Martín       None    None
3     Ana     Sofía  Hernández    Ruiz
4    Luis  González       None    None

In [84]:
# División con límites y desde la derecha
print("\n🎯 División avanzada:")

# Emails para extraer usuario y dominio
emails_division = pd.Series([
    'usuario@empresa.com',
    'nombre.apellido@universidad.edu.es',
    'test@sub.dominio.org',
    'admin@localhost'
])

print("División de emails:")
print("Emails originales:", emails_division.tolist())

# División por @ con límite
email_partes = emails_division.str.split('@', n=1, expand=True)
email_partes.columns = ['Usuario', 'Dominio_Completo']
print("\nDivisión por @:")
display(email_partes)

🎯 División avanzada:
División de emails:
Emails originales: ['usuario@empresa.com', 'nombre.apellido@universidad.edu.es', 'test@sub.dominio.org', 'admin@localhost']

División por @:

           Usuario    Dominio_Completo
0          usuario         empresa.com
1  nombre.apellido  universidad.edu.es
2             test     sub.dominio.org
3            admin           localhost

In [85]:

# División del dominio por puntos (desde la derecha)
dominios = email_partes['Dominio_Completo']
dominio_partes = dominios.str.rsplit('.', n=1, expand=True)
dominio_partes.columns = ['Dominio_Base', 'Extension']

# Combinar resultados
df_emails_completo = pd.DataFrame({
    'Email_Original': emails_division,
    'Usuario': email_partes['Usuario'],
    'Dominio_Base': dominio_partes['Dominio_Base'],
    'Extension': dominio_partes['Extension']
})
print("\nAnálisis completo de emails:")
display(df_emails_completo)

Análisis completo de emails:

                       Email_Original          Usuario     Dominio_Base Extension
0                 usuario@empresa.com          usuario          empresa       com
1  nombre.apellido@universidad.edu.es  nombre.apellido  universidad.edu        es
2                test@sub.dominio.org             test      sub.dominio       org
3                     admin@localhost            admin        localhost      None

In [86]:
# Unión de strings con .str.cat()
print("\n🔗 Unión de strings:")

# Crear DataFrame con partes separadas
datos_separados = pd.DataFrame({
    'nombre': ['Juan', 'María', 'Pedro'],
    'apellido1': ['Pérez', 'García', 'Rodríguez'],
    'apellido2': ['López', 'Martín', 'Hernández']
})

print("Datos separados:")
display(datos_separados)

🔗 Unión de strings:
Datos separados:

  nombre  apellido1  apellido2
0   Juan      Pérez      López
1  María     García     Martín
2  Pedro  Rodríguez  Hernández

In [87]:

# Unir con .str.cat()
nombres_unidos = datos_separados['nombre'].str.cat(
    [datos_separados['apellido1'], datos_separados['apellido2']], 
    sep=' '
)
print(f"\nNombres unidos: {nombres_unidos.tolist()}")

# Unir con separadores personalizados
emails_construidos = datos_separados['nombre'].str.cat(
    datos_separados['apellido1'], 
    sep='.'
).str.lower() + '@empresa.com'

print(f"Emails construidos: {emails_construidos.tolist()}")

Nombres unidos: ['Juan Pérez López', 'María García Martín', 'Pedro Rodríguez Hernández']
Emails construidos: ['juan.pérez@empresa.com', 'maría.garcía@empresa.com', 'pedro.rodríguez@empresa.com']

In [88]:
# Caso práctico: reestructuración de datos
print("\n📊 Caso práctico: Reestructuración de datos CSV:")

# Simular datos que vienen en formato incorrecto
datos_csv_malo = pd.Series([
    'Juan,Pérez,25,Madrid',
    'María,García,30,Barcelona',
    'Pedro,Rodríguez,28,Valencia',
    'Ana,López,35,Sevilla'
])

print("Datos CSV en una columna:")
print(datos_csv_malo.tolist())

# Dividir en columnas apropiadas
datos_estructurados = datos_csv_malo.str.split(',', expand=True)
datos_estructurados.columns = ['Nombre', 'Apellido', 'Edad', 'Ciudad']

# Limpiar y convertir tipos
datos_estructurados['Edad'] = pd.to_numeric(datos_estructurados['Edad'])
datos_estructurados['Nombre'] = datos_estructurados['Nombre'].str.title()
datos_estructurados['Apellido'] = datos_estructurados['Apellido'].str.title()

print("\nDatos reestructurados:")
display(datos_estructurados)

📊 Caso práctico: Reestructuración de datos CSV:
Datos CSV en una columna:
['Juan,Pérez,25,Madrid', 'María,García,30,Barcelona', 'Pedro,Rodríguez,28,Valencia', 'Ana,López,35,Sevilla']

Datos reestructurados:

  Nombre   Apellido  Edad     Ciudad
0   Juan      Pérez    25     Madrid
1  María     García    30  Barcelona
2  Pedro  Rodríguez    28   Valencia
3    Ana      López    35    Sevilla

In [89]:

print(f"\nTipos de datos:\n{datos_estructurados.dtypes}")

# Crear identificadores únicos
datos_estructurados['ID'] = (
    datos_estructurados['Nombre'].str[:2].str.upper() + 
    datos_estructurados['Apellido'].str[:2].str.upper() + 
    datos_estructurados['Edad'].astype(str)
)

print("\nCon IDs generados:")
display(datos_estructurados[['ID', 'Nombre', 'Apellido', 'Edad', 'Ciudad']])

Tipos de datos:
Nombre      object
Apellido    object
Edad         int64
Ciudad      object
dtype: object

Con IDs generados:

       ID Nombre   Apellido  Edad     Ciudad
0  JUPÉ25   Juan      Pérez    25     Madrid
1  MAGA30  María     García    30  Barcelona
2  PERO28  Pedro  Rodríguez    28   Valencia
3  ANLÓ35    Ana      López    35    Sevilla

## 10. Trabajar con Datos Categóricos de Texto {#10}

La conversión de texto a categorías y la creación de variables dummy son técnicas importantes en análisis de datos:

In [90]:
# Conversión a categorías
print("📊 Conversión de texto a categorías:")

# Datos categóricos típicos
categorias_texto = pd.Series([
    'Alto', 'Medio', 'Bajo', 'Alto', 'Medio', 
    'Bajo', 'Alto', 'Medio', 'Alto', 'Bajo'
] * 2)  # Repetir para tener más datos

print(f"Datos originales (string): {categorias_texto.dtype}")
print(f"Valores únicos: {categorias_texto.unique()}")
print(f"Memoria usada: {categorias_texto.memory_usage(deep=True)} bytes")

# Convertir a categorical
categorias_cat = categorias_texto.astype('category')
print(f"\nDespués de conversión:")
print(f"Tipo: {categorias_cat.dtype}")
print(f"Categorías: {categorias_cat.cat.categories.tolist()}")
print(f"Memoria usada: {categorias_cat.memory_usage(deep=True)} bytes")
print(f"Ahorro de memoria: {((categorias_texto.memory_usage(deep=True) - categorias_cat.memory_usage(deep=True)) / categorias_texto.memory_usage(deep=True) * 100):.1f}%")

📊 Conversión de texto a categorías:
Datos originales (string): object
Valores únicos: ['Alto' 'Medio' 'Bajo']
Memoria usada: 1198 bytes

Después de conversión:
Tipo: category
Categorías: ['Alto', 'Bajo', 'Medio']
Memoria usada: 420 bytes
Ahorro de memoria: 64.9%

In [91]:
# Ordenar categorías
print("\n📶 Ordenamiento de categorías:")

# Crear categorías con orden lógico
niveles_educacion = pd.Series([
    'Universidad', 'Secundaria', 'Primaria', 'Master', 
    'Universidad', 'Doctorado', 'Secundaria', 'Primaria'
])

print("Niveles de educación (desordenados):")
print(niveles_educacion.tolist())

# Convertir a categorical con orden
orden_educacion = ['Primaria', 'Secundaria', 'Universidad', 'Master', 'Doctorado']
niveles_ordenados = pd.Categorical(niveles_educacion, categories=orden_educacion, ordered=True)

df_educacion = pd.DataFrame({
    'Original': niveles_educacion,
    'Ordenado': niveles_ordenados
})

print("\nConversión a categorical ordenado:")
display(df_educacion)

# Verificar ordenamiento
print(f"\n¿Es ordenado? {niveles_ordenados.ordered}")
print(f"Orden: {niveles_ordenados.categories.tolist()}")

# Ordenar DataFrame por categoría
df_ordenado = df_educacion.sort_values('Ordenado')
print("\nDataFrame ordenado por nivel educativo:")
display(df_ordenado)

📶 Ordenamiento de categorías:
Niveles de educación (desordenados):
['Universidad', 'Secundaria', 'Primaria', 'Master', 'Universidad', 'Doctorado', 'Secundaria', 'Primaria']

Conversión a categorical ordenado:

      Original     Ordenado
0  Universidad  Universidad
1   Secundaria   Secundaria
2     Primaria     Primaria
3       Master       Master
4  Universidad  Universidad
5    Doctorado    Doctorado
6   Secundaria   Secundaria
7     Primaria     Primaria

¿Es ordenado? True
Orden: ['Primaria', 'Secundaria', 'Universidad', 'Master', 'Doctorado']

DataFrame ordenado por nivel educativo:

      Original     Ordenado
2     Primaria     Primaria
7     Primaria     Primaria
1   Secundaria   Secundaria
6   Secundaria   Secundaria
0  Universidad  Universidad
4  Universidad  Universidad
3       Master       Master
5    Doctorado    Doctorado

In [93]:
# Variables dummy con .str.get_dummies()
print("\n🎭 Creación de variables dummy:")

# Datos con múltiples categorías por observación
habilidades = pd.Series([
    'Python,SQL,Excel',
    'R,Python,Tableau',
    'SQL,Excel',
    'Python,R,SQL,Tableau',
    'Excel,Power BI'
])

print("Habilidades por persona:")
print(habilidades.tolist())

# Crear variables dummy
dummies = habilidades.str.get_dummies(sep=',')
print("\nVariables dummy creadas:")
display(dummies)

# Agregar identificador de persona
dummies['Persona'] = [f'Persona_{i+1}' for i in range(len(dummies))]
cols = ['Persona'] + [col for col in dummies.columns if col != 'Persona']
dummies = dummies[cols]

print("\nCon identificador de persona:")
display(dummies)

🎭 Creación de variables dummy:
Habilidades por persona:
['Python,SQL,Excel', 'R,Python,Tableau', 'SQL,Excel', 'Python,R,SQL,Tableau', 'Excel,Power BI']

Variables dummy creadas:

   Excel  Power BI  Python  R  SQL  Tableau
0      1         0       1  0    1        0
1      0         0       1  1    0        1
2      1         0       0  0    1        0
3      0         0       1  1    1        1
4      1         1       0  0    0        0

Con identificador de persona:

     Persona  Excel  Power BI  Python  R  SQL  Tableau
0  Persona_1      1         0       1  0    1        0
1  Persona_2      0         0       1  1    0        1
2  Persona_3      1         0       0  0    1        0
3  Persona_4      0         0       1  1    1        1
4  Persona_5      1         1       0  0    0        0

In [94]:
# Mapeo de categorías
print("\n🗺️ Mapeo de categorías:")

# Datos categóricos que necesitan mapeo
satisfaccion = pd.Series([
    'Muy Satisfecho', 'Satisfecho', 'Neutral', 
    'Insatisfecho', 'Muy Insatisfecho', 'Satisfecho',
    'Muy Satisfecho', 'Neutral', 'Insatisfecho'
])

print("Datos de satisfacción:")
print(satisfaccion.tolist())

# Mapeo a valores numéricos
mapeo_satisfaccion = {
    'Muy Insatisfecho': 1,
    'Insatisfecho': 2,
    'Neutral': 3,
    'Satisfecho': 4,
    'Muy Satisfecho': 5
}

satisfaccion_numerica = satisfaccion.map(mapeo_satisfaccion)

# Mapeo a categorías simplificadas
mapeo_simplificado = {
    'Muy Insatisfecho': 'Negativo',
    'Insatisfecho': 'Negativo',
    'Neutral': 'Neutro',
    'Satisfecho': 'Positivo',
    'Muy Satisfecho': 'Positivo'
}

satisfaccion_simple = satisfaccion.map(mapeo_simplificado)

# Crear DataFrame comparativo
df_mapeo = pd.DataFrame({
    'Original': satisfaccion,
    'Numérico': satisfaccion_numerica,
    'Simplificado': satisfaccion_simple
})

print("\nResultados del mapeo:")
display(df_mapeo)

# Estadísticas por categoría
print("\n📈 Estadísticas por categoría:")
print(f"Promedio satisfacción numérica: {satisfaccion_numerica.mean():.2f}")
print("Distribución simplificada:")
print(satisfaccion_simple.value_counts())

🗺️ Mapeo de categorías:
Datos de satisfacción:
['Muy Satisfecho', 'Satisfecho', 'Neutral', 'Insatisfecho', 'Muy Insatisfecho', 'Satisfecho', 'Muy Satisfecho', 'Neutral', 'Insatisfecho']

Resultados del mapeo:

           Original  Numérico Simplificado
0    Muy Satisfecho         5     Positivo
1        Satisfecho         4     Positivo
2           Neutral         3       Neutro
3      Insatisfecho         2     Negativo
4  Muy Insatisfecho         1     Negativo
5        Satisfecho         4     Positivo
6    Muy Satisfecho         5     Positivo
7           Neutral         3       Neutro
8      Insatisfecho         2     Negativo

📈 Estadísticas por categoría:
Promedio satisfacción numérica: 3.22
Distribución simplificada:
Positivo    4
Negativo    3
Neutro      2
Name: count, dtype: int64

## 11. Análisis de Texto y Conteos {#11}

Las métricas de texto son fundamentales para el análisis exploratorio de datos textuales:

In [96]:
# Métricas básicas de texto
print("📏 Métricas básicas de texto:")

# Datos de ejemplo para análisis
comentarios = pd.Series([
    'Excelente producto, muy recomendado',
    'Regular, podría mejorar',
    'Perfecto! Lo compraré de nuevo sin duda',
    'No me gustó nada',
    'Buena calidad precio, satisfecho con la compra'
])

print("Comentarios de productos:")
for i, comentario in enumerate(comentarios):
    print(f"{i+1}. {comentario}")

# Calcular métricas
df_metricas = pd.DataFrame({
    'Comentario': comentarios,
    'Longitud': comentarios.str.len(),
    'Num_Palabras': comentarios.str.split().str.len(),
    'Num_Caracteres_Sin_Espacios': comentarios.str.replace(' ', '').str.len(),
    'Tiene_Signos_Exclamacion': comentarios.str.contains('!'),
    'Empieza_Mayuscula': comentarios.str[0].str.isupper()
})

print("\n📊 Métricas calculadas:")
display(df_metricas)

📏 Métricas básicas de texto:
Comentarios de productos:
1. Excelente producto, muy recomendado
2. Regular, podría mejorar
3. Perfecto! Lo compraré de nuevo sin duda
4. No me gustó nada
5. Buena calidad precio, satisfecho con la compra

📊 Métricas calculadas:

                                       Comentario  Longitud  Num_Palabras  Num_Caracteres_Sin_Espacios  Tiene_Signos_Exclamacion  Empieza_Mayuscula
0             Excelente producto, muy recomendado        35             4                           32                     False               True
1                         Regular, podría mejorar        23             3                           21                     False               True
2         Perfecto! Lo compraré de nuevo sin duda        39             7                           33                      True               True
3                                No me gustó nada        16             4                           13                     False               True
4  Buena calidad precio, satisfecho con la compra        46             7                           40                     False               True

In [99]:
# Conteos específicos
print("\n🔢 Conteos específicos:")

# Datos con patrones a contar
textos_conteo = pd.Series([
    'El análisis de datos es fascinante',
    'Python y pandas son herramientas poderosas',
    'Los datos nos ayudan a tomar decisiones',
    'Visualización de datos con Python',
    'Machine learning con datos limpios'
])

print("Textos para análisis:")
print(textos_conteo.tolist())

# Diferentes tipos de conteos
df_conteos = pd.DataFrame({
    'Texto': textos_conteo,
    'Veces_datos': textos_conteo.str.count('datos'),
    'Veces_Python': textos_conteo.str.count('Python'),
    'Veces_vocal_a': textos_conteo.str.count('[aáA]'),
    'Contiene_Python': textos_conteo.str.contains('Python'),
    'Longitud_Total': textos_conteo.str.len()
})

print("\n📈 Conteos realizados:")
display(df_conteos)

# Estadísticas de los conteos
print(f"\nEstadísticas generales:")
print(f"Promedio de menciones de 'datos': {df_conteos['Veces_datos'].mean():.2f}")
print(f"Textos que mencionan 'Python': {df_conteos['Contiene_Python'].sum()}")
print(f"Longitud promedio de texto: {df_conteos['Longitud_Total'].mean():.1f} caracteres")

🔢 Conteos específicos:
Textos para análisis:
['El análisis de datos es fascinante', 'Python y pandas son herramientas poderosas', 'Los datos nos ayudan a tomar decisiones', 'Visualización de datos con Python', 'Machine learning con datos limpios']

📈 Conteos realizados:

                                        Texto  Veces_datos  Veces_Python  Veces_vocal_a  Contiene_Python  Longitud_Total
0          El análisis de datos es fascinante            1             0              5            False              34
1  Python y pandas son herramientas poderosas            0             1              5             True              42
2     Los datos nos ayudan a tomar decisiones            1             0              5            False              39
3           Visualización de datos con Python            1             1              3             True              33
4          Machine learning con datos limpios            1             0              3            False              34

Estadísticas generales:
Promedio de menciones de 'datos': 0.80
Textos que mencionan 'Python': 2
Longitud promedio de texto: 36.4 caracteres

In [100]:
# Análisis de frecuencia de palabras
print("\n🔍 Análisis de frecuencia de palabras:")

# Textos más largos para análisis
textos_largos = pd.Series([
    'El análisis de datos es fundamental para la toma de decisiones en las empresas modernas',
    'Python se ha convertido en el lenguaje preferido para ciencia de datos y análisis',
    'La visualización de datos ayuda a comunicar insights de manera efectiva',
    'Machine learning y deep learning están revolucionando múltiples industrias',
    'Los datos son el nuevo petróleo de la economía digital moderna'
])

print("Textos para análisis de frecuencia:")
for i, texto in enumerate(textos_largos):
    print(f"{i+1}. {texto}")

# Función para análisis de palabras
def analizar_palabras(serie_textos):
    """Analiza frecuencia de palabras en una serie"""
    # Unir todos los textos
    texto_completo = ' '.join(serie_textos.dropna())
    
    # Limpiar y dividir en palabras
    palabras = (texto_completo
                .lower()
                .replace('.', '')
                .replace(',', '')
                .split())
    
    # Contar frecuencias
    from collections import Counter
    contador = Counter(palabras)
    
    return contador

frecuencias = analizar_palabras(textos_largos)
print(f"\n📊 Palabras más frecuentes:")
for palabra, freq in frecuencias.most_common(10):
    print(f"'{palabra}': {freq} veces")

# Palabras únicas por texto
palabras_unicas = textos_largos.str.split().apply(lambda x: len(set(x)) if x else 0)
print(f"\nPalabras únicas por texto: {palabras_unicas.tolist()}")

# Diversidad léxica (palabras únicas / total palabras)
total_palabras = textos_largos.str.split().str.len()
diversidad = (palabras_unicas / total_palabras).round(2)
print(f"Diversidad léxica por texto: {diversidad.tolist()}")

🔍 Análisis de frecuencia de palabras:
Textos para análisis de frecuencia:
1. El análisis de datos es fundamental para la toma de decisiones en las empresas modernas
2. Python se ha convertido en el lenguaje preferido para ciencia de datos y análisis
3. La visualización de datos ayuda a comunicar insights de manera efectiva
4. Machine learning y deep learning están revolucionando múltiples industrias
5. Los datos son el nuevo petróleo de la economía digital moderna

📊 Palabras más frecuentes:
'de': 6 veces
'datos': 4 veces
'el': 3 veces
'la': 3 veces
'análisis': 2 veces
'para': 2 veces
'en': 2 veces
'y': 2 veces
'learning': 2 veces
'es': 1 veces

Palabras únicas por texto: [14, 14, 10, 8, 11]
Diversidad léxica por texto: [0.93, 1.0, 0.91, 0.89, 1.0]

In [103]:
# Análisis comparativo de longitudes
print("\n📐 Análisis comparativo de longitudes:")

# Diferentes tipos de texto
tipos_texto = pd.DataFrame({
    'Tweets': ['Excelente día! #feliz', 'Trabajando en #datascience', 'Python es genial! 🐍'],
    'Emails': [
        'Estimado cliente, le informamos que su pedido está listo',
        'Reunión programada para mañana a las 10:00 AM en sala de juntas',
        'Felicitaciones por su promoción, bien merecida'
    ],
    'Artículos': [
        'El impacto de la inteligencia artificial en la sociedad moderna es un tema complejo que requiere análisis profundo',
        'Los algoritmos de machine learning están transformando la manera en que las empresas toman decisiones estratégicas',
        'La importancia de la visualización de datos radica en su capacidad para comunicar insights complejos de forma simple'
    ]
})

# Calcular estadísticas por tipo
estadisticas_tipo = {}
for columna in tipos_texto.columns:
    serie = tipos_texto[columna]
    estadisticas_tipo[columna] = {
        'longitud_promedio': serie.str.len().mean(),
        'palabras_promedio': serie.str.split().str.len().mean(),
        'longitud_min': serie.str.len().min(),
        'longitud_max': serie.str.len().max()
    }

df_estadisticas = pd.DataFrame(estadisticas_tipo).round(1)
print("Estadísticas por tipo de texto:")
print(df_estadisticas)

# Visualizar diferencias
print(f"\n📊 Comparación visual:")
for tipo in tipos_texto.columns:
    longitudes = tipos_texto[tipo].str.len()
    print(f"{tipo:12}: {'█' * int(longitudes.mean() / 10):15} ({longitudes.mean():.0f} chars promedio)")

📐 Análisis comparativo de longitudes:
Estadísticas por tipo de texto:
                   Tweets  Emails  Artículos
longitud_promedio    22.0    55.0      114.7
palabras_promedio     3.3     9.0       17.3
longitud_min         19.0    46.0      114.0
longitud_max         26.0    63.0      116.0

📊 Comparación visual:
Tweets      : ██              (22 chars promedio)
Emails      : █████           (55 chars promedio)
Artículos   : ███████████     (115 chars promedio)

## 12. Casos Prácticos en Data Analytics {#12}

Aplicaciones reales del manejo de strings en proyectos de Data Analytics:

In [104]:
# Caso 1: Limpieza de dataset de clientes
print("👥 Caso 1: Limpieza de dataset de clientes")

# Simular datos sucios de clientes
clientes_sucios = pd.DataFrame({
    'nombre_completo': [
        '  JOSÉ MARÍA PÉREZ GARCÍA  ',
        'maría josé Rodríguez López\t',
        'Dr. Pedro   Martín   Hernández',
        'Dña.\tAna Sofía\tGonzález Ruiz',
        'luis   HERNÁNDEZ   moreno   '
    ],
    'email': [
        'JOSE.PEREZ@GMAIL.COM',
        'maria.rodriguez@EMPRESA.es',
        '  pedro.martin@universidad.EDU  ',
        'ana.gonzalez@startup.io',
        'luis@CONSULTORA.COM   '
    ],
    'telefono': [
        '+34 612-345-678',
        '34.123.456.789',
        '612 345 678',
        '+1-555-0123',
        '91 234 56 78'
    ],
    'direccion': [
        'Calle Mayor 123, 4º B, 28001 MADRID',
        'Av. Diagonal 456  08001 barcelona',
        'Plaza España 789, 1º A, 46001 Valencia',
        'Calle Luna 321, 2º C, 41001 SEVILLA',
        'Gran Vía 654, Ático, 48001 Bilbao'
    ]
})

print("Datos originales (sucios):")
display(clientes_sucios)

👥 Caso 1: Limpieza de dataset de clientes
Datos originales (sucios):

                  nombre_completo                             email         telefono                               direccion
0       JOSÉ MARÍA PÉREZ GARCÍA                JOSE.PEREZ@GMAIL.COM  +34 612-345-678     Calle Mayor 123, 4º B, 28001 MADRID
1    maría josé Rodríguez López\t        maria.rodriguez@EMPRESA.es   34.123.456.789       Av. Diagonal 456  08001 barcelona
2  Dr. Pedro   Martín   Hernández    pedro.martin@universidad.EDU        612 345 678  Plaza España 789, 1º A, 46001 Valencia
3  Dña.\tAna Sofía\tGonzález Ruiz           ana.gonzalez@startup.io      +1-555-0123     Calle Luna 321, 2º C, 41001 SEVILLA
4    luis   HERNÁNDEZ   moreno               luis@CONSULTORA.COM        91 234 56 78       Gran Vía 654, Ático, 48001 Bilbao

In [105]:
# Pipeline de limpieza completo
def limpiar_dataset_clientes(df):
    """Pipeline completo de limpieza para datos de clientes"""
    df_limpio = df.copy()
    
    # 1. Limpiar nombres
    df_limpio['nombre_limpio'] = (df['nombre_completo']
                                  .str.strip()
                                  .str.replace('\t', ' ', regex=False)
                                  .str.replace(r'\s+', ' ', regex=True)
                                  .str.replace(r'^(Dr\.|Dra\.|D\.|Dña\.)\s*', '', regex=True)
                                  .str.title())
    
    # 2. Limpiar emails
    df_limpio['email_limpio'] = (df['email']
                                 .str.strip()
                                 .str.lower())
    
    # 3. Normalizar teléfonos
    def normalizar_telefono(telefono):
        if pd.isna(telefono):
            return telefono
        # Extraer solo dígitos
        digitos = re.sub(r'\D', '', str(telefono))
        # Formatear según longitud
        if len(digitos) == 9:  # Nacional
            return f"+34 {digitos[:3]} {digitos[3:6]} {digitos[6:]}"
        elif len(digitos) == 11 and digitos.startswith('34'):  # Con código país
            return f"+34 {digitos[2:5]} {digitos[5:8]} {digitos[8:]}"
        else:
            return telefono
    
    df_limpio['telefono_limpio'] = df['telefono'].apply(normalizar_telefono)
    
    # 4. Extraer información de direcciones
    patron_direccion = r'^(.+?),.*?(\d{5})\s+([A-Za-záéíóúñ]+)$'
    direccion_partes = df['direccion'].str.extract(patron_direccion)
    
    df_limpio['calle'] = direccion_partes[0].str.strip().str.title()
    df_limpio['codigo_postal'] = direccion_partes[1]
    df_limpio['ciudad'] = direccion_partes[2].str.title()
    
    return df_limpio

# Aplicar limpieza
clientes_limpios = limpiar_dataset_clientes(clientes_sucios)

print("\nDatos después de limpieza:")
columnas_mostrar = ['nombre_limpio', 'email_limpio', 'telefono_limpio', 'ciudad']
display(clientes_limpios[columnas_mostrar])

Datos después de limpieza:

                nombre_limpio                  email_limpio  telefono_limpio    ciudad
0     José María Pérez García          jose.perez@gmail.com  +34 612 345 678    Madrid
1  María José Rodríguez López    maria.rodriguez@empresa.es  +34 123 456 789       NaN
2      Pedro Martín Hernández  pedro.martin@universidad.edu  +34 612 345 678  Valencia
3     Ana Sofía González Ruiz       ana.gonzalez@startup.io      +1-555-0123   Sevilla
4       Luis Hernández Moreno           luis@consultora.com  +34 912 345 678    Bilbao

In [106]:
# Caso 2: Análisis de URLs de tráfico web
print("\n🌐 Caso 2: Análisis de URLs de tráfico web")

# Simular log de URLs
urls_trafico = pd.Series([
    'https://www.tienda.com/productos/laptops?categoria=gaming&precio=alto',
    'https://www.tienda.com/productos/moviles?marca=apple&storage=256gb',
    'http://www.tienda.com/ofertas/black-friday?descuento=50',
    'https://www.tienda.com/productos/tablets?marca=samsung&pantalla=10inch',
    'https://www.tienda.com/soporte/contacto?tipo=devolucion',
    'https://www.tienda.com/productos/accesorios?categoria=audifonos&precio=medio',
    'http://www.tienda.com/ofertas/cyber-monday?descuento=30'
])

print("URLs de tráfico web:")
for i, url in enumerate(urls_trafico):
    print(f"{i+1}. {url}")

# Análisis de URLs
def analizar_urls(serie_urls):
    """Analiza componentes de URLs"""
    
    # Extraer componentes principales
    patron_url = r'(https?)://([^/]+)(/[^?]*)?(\?.*)?'
    componentes = serie_urls.str.extract(patron_url)
    componentes.columns = ['Protocolo', 'Dominio', 'Path', 'Query']
    
    # Extraer sección principal del path
    componentes['Seccion'] = (componentes['Path']
                              .str.split('/')
                              .str[1]
                              .fillna('home'))
    
    # Extraer subsección
    componentes['Subseccion'] = (componentes['Path']
                                 .str.split('/')
                                 .str[2]
                                 .fillna('index'))
    
    # Contar parámetros de query
    componentes['Num_Parametros'] = (componentes['Query']
                                     .str.count('&')
                                     .fillna(0) + 1)
    # Ajustar para URLs sin query
    componentes.loc[componentes['Query'].isna(), 'Num_Parametros'] = 0
    
    return componentes

analisis_urls = analizar_urls(urls_trafico)
print("\n📊 Análisis de URLs:")
print(analisis_urls[['Protocolo', 'Seccion', 'Subseccion', 'Num_Parametros']])

# Estadísticas del tráfico
print(f"\n📈 Estadísticas del tráfico:")
print("Secciones más visitadas:")
print(analisis_urls['Seccion'].value_counts())

print(f"\nUso de protocolo seguro (HTTPS): {(analisis_urls['Protocolo'] == 'https').sum()}/{len(analisis_urls)}")
print(f"Promedio de parámetros por URL: {analisis_urls['Num_Parametros'].mean():.1f}")

🌐 Caso 2: Análisis de URLs de tráfico web
URLs de tráfico web:
1. https://www.tienda.com/productos/laptops?categoria=gaming&precio=alto
2. https://www.tienda.com/productos/moviles?marca=apple&storage=256gb
3. http://www.tienda.com/ofertas/black-friday?descuento=50
4. https://www.tienda.com/productos/tablets?marca=samsung&pantalla=10inch
5. https://www.tienda.com/soporte/contacto?tipo=devolucion
6. https://www.tienda.com/productos/accesorios?categoria=audifonos&precio=medio
7. http://www.tienda.com/ofertas/cyber-monday?descuento=30

📊 Análisis de URLs:
  Protocolo    Seccion    Subseccion  Num_Parametros
0     https  productos       laptops               2
1     https  productos       moviles               2
2      http    ofertas  black-friday               1
3     https  productos       tablets               2
4     https    soporte      contacto               1
5     https  productos    accesorios               2
6      http    ofertas  cyber-monday               1

📈 Estadísticas del tráfico:
Secciones más visitadas:
Seccion
productos    4
ofertas      2
soporte      1
Name: count, dtype: int64

Uso de protocolo seguro (HTTPS): 5/7
Promedio de parámetros por URL: 1.6